In [33]:
import sys
import os
import re
sys.path.insert(0, os.path.abspath('..'))

from pdfquery import PDFQuery
import fitz
import pandas as pd
from utils.utilities import (
    convertir_pdf_a_xml
)
from src.scrap_pdf_AG import (
    check_format,
    get_PESO_BRUTO,
    get_ADUANA_DESTINO,
    get_CRT,
    get_DDT,
    get_DESTINATARIO,
    get_DESTINO,
    get_SEMI,
    get_TRACTOR,
    get_TRANSPORTE_CAMPO_1,
    get_TRANSPORTE_CAMPO_9,
)
from utils.utilities import (
    listar_archivos_pdf
)

def test_func(function):
    for i in archivos[:10:2]:
        pdf = PDFQuery(i)
        pdf.load(0)
        print(function(pdf))
        

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

In [18]:
archivos = listar_archivos_pdf('C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026')

In [19]:
archivos

['C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR052590X.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR067657S.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR067725Y.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR067733N.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR067745Z.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR067751N.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR067755R.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR067758U.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR067764R.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR067772Z.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR067795V.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR067831M.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR067836R.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR067845R.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR067855S.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR067860Y.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR067890R.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR067899D.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR067905Y.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR067911L.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR067916Z.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR067923Y.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR067930M.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR067940N.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR067950Y.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR067958W.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR068183N.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR068185P.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR068188S.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR068195Z.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR068202F.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR068205X.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR068208L.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR072813X.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR072831X.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR073107F.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR073113C.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR073118H.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR073124E.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR073130B.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR073141D.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR073143F.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR073151E.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR073156J.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR073162G.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR074767S.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR074771N.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR074785S.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077514L.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077525N.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077533M.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077534N.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077541L.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077556R.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077559U.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077564Z.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077570N.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077578V.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077584S.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077590P.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077595U.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077602J.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077606N.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077607Y.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077642N.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077650M.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077660N.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077669W.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077675T.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077722M.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077727R.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077731M.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077734P.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077738T.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077741N.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077746S.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077758V.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077761P.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077766U.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077768W.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077773S.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077777W.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077778A.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077781R.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077787A.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077791S.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077793U.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077796A.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077801K.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077808R.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077810K.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077819T.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077821M.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077825Z.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077828T.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077832Y.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077839V.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077842P.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077844R.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077849W.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077856U.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077859A.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077861Z.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077867W.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077875V.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077878B.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077882T.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077886A.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077890S.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077891T.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077893V.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077902M.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077903N.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077909T.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077913Y.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077916R.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077919U.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077920M.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077926S.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077929V.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077948W.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077950P.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077954T.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR077959B.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR079269U.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR079273P.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR079277T.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR079282P.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR079286T.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR079292Z.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR079308Y.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR079313K.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR079316N.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR079320X.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR079322K.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR079326Y.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR079329R.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR079336P.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR083513H.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR083517L.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR083527M.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR083531H.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR083534K.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR083539P.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR083541X.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR083545M.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR083550X.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR083553L.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR083557P.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR083561K.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR083563M.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR083566P.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR083570K.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR083574Y.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR083578S.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR083592Y.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR083594Z.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR083596S.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR083602G.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR083605J.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR083611G.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR083615K.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR083619Y.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR083622X.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR083624K.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR083628Y.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR083643L.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR083649R.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR083653M.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR083657Z.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR083662M.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR083667R.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR083672N.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR086297T.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR086311G.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR086321H.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR086340X.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR086361L.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR087917T.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR088129P.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR088131X.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR088134L.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR088143L.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR088145N.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR088146Y.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR088154N.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR088703N.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR088712N.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR088716R.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR088720M.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR088724Z.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR088728U.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR088733Z.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR088739W.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR088743R.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR089009N.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR089011G.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR089015K.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR089019Y.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR089022X.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR089023J.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR089024K.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR089028Y.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR089030H.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR089033K.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR089035M.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR089256R.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR089260M.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR089261N.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR089265R.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR089266S.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR089268U.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR089271Y.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR089273Z.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR089276T.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR089279W.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR089280Y.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR089282Z.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR089286U.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR089290P.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR089450N.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR089452P.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR089454R.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR089459W.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR089463R.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR089464S.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR089468W.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR089470P.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR089478A.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR089483T.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR089487A.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR089491S.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR090116E.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR090142D.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR090185K.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR090705X.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR090709M.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR092017G.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR092020A.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR092023D.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR092024E.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR092148L.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR092157L.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR092166L.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR092202C.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR094263L.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR094264M.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR094267P.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR094269R.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR094273M.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR094275Y.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR094749U.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR094753P.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR094759V.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR094764R.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR094765S.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR094768V.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR094771P.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR094772Z.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR094776U.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR094779A.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR094788A.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR094794U.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR094801J.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR094822M.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR094826Z.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR094831M.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR094836R.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR094929U.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR094934Z.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR094941Y.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR094947U.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR094954S.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR094958W.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR094964T.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR094966V.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR094970Z.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR094995A.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR095000B.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR095001C.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR095004F.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR095007X.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR095020D.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR095024H.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR095029M.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR095035J.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR095040F.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR095045K.pdf',
 'C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR095053J.pdf',

In [20]:

archivo = archivos[20]

In [27]:
convertir_pdf_a_xml('C:\\Rapha\\repos\\pdfs-to-excel-1\\data\\AG2026\\26AR067855S.pdf', output_path='data/archivo.xml')

FileNotFoundError: [Errno 2] No such file or directory

In [31]:
for archivo in archivos:
    pdf = PDFQuery(archivo)
    pdf.load(0)

    print(get_TRANSPORTE_CAMPO_99(pdf))

NameError: name 'get_TRANSPORTE_CAMPO_99' is not defined

In [ ]:


import re
import fitz
import pandas as pd

def get_TRANSPORTE_CAMPO_9_1(archivos: list[str]):
    """_summary_

    Args:
        archivo (str): _description_

    Returns:
        _type_: _description_
    """
    
    data = []
    for archivo in archivos:
    
        pdf = fitz.open(archivo).load_page(0)
        # Load the page content as text
        page_text = pdf.get_text("text")

        texto_antes = 'CAMINH?O ORIGINAL : Nome e endereco do proprietario\n9\n'
        texto_despues = 'CAMION SUBSTITUTO : Nombre y domicilio del propietario'

        pattern = re.escape(texto_antes) + r"(.*?)" + re.escape(texto_despues)
        
        matches = re.findall(pattern, page_text, re.DOTALL)

        data.append(matches[0].split('- ')[0].strip()) if matches else None
    
    return data

get_TRANSPORTE_CAMPO_9_1(archivos)

In [34]:
def get_PRECINTO(pdf: PDFQuery):
    
    text  =  pdf.pq('LTTextLineHorizontal:contains("37 Numero de los precintos")').next().text()
    return text

In [35]:
for archivo in archivos:
    pdf = PDFQuery(archivo)
    pdf.load(0)
    print(get_PRECINTO(pdf))

JK86876
JK86875
JK86877
JK88513
JK88514
JK86880
JK88515
JK88516
JK88517
JK86777

c:\Users\rapha\AppData\Local\Programs\Python\Python313\Lib\site-packages\pdfquery\pdfquery.py:475: SyntaxWarning: invalid escape sequence '\W'
  k = re.sub('\W', '_', k)

KeyboardInterrupt:

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_excel('data/agtest1.xlsx',sheet_name='Sheet1', header=0, engine='openpyxl')
df

# hacer un grafico de torta con TRANSPORTE CAMPO 1 Y QUE SUME POR CDA UNO CANTIDAD BULTOS, ponemelo en cantidad
df.groupby('TRANSPORTE CAMPO 1')['KILOS BRUTOS'].sum().plot.pie(autopct='%1.1f%%', startangle=90, figsize=(8, 8))

In [36]:
def get_EXPORTADOR(pdf: PDFQuery):
    text  =  pdf.pq('LTTextLineHorizontal:contains("/ Remetente")').next().text()
    return text

In [37]:
data = []
for archivo in archivos:
    pdf = PDFQuery(archivo)
    pdf.load(0)
    data.append(get_DESTINATARIO(pdf))

TypeError: 'PDFQuery' object is not iterable

In [39]:
def get_DESTINATARIO(pdf: PDFQuery):
    text  =  pdf.pq('LTTextLineHorizontal:contains("34 Destinatario / Destinatario")').next().text()
    return text

pdf = PDFQuery(archivos[1])
pdf.load(0)
get_DESTINATARIO(pdf)

'SM RESINAS URUGUAY SA'

In [40]:
data = []
for archivo in archivos:
    
    pdf = fitz.open(archivo).load_page(0)
        # Load the page content as text
    page_text = pdf.get_text("text")

    #print(page_text)

    texto_antes = '/ Destinatario'
    texto_despues = '35 Consignatario /Consignatario'
    pattern = re.escape(texto_antes) + r"(.*)" + re.escape(texto_despues)
    matches = re.findall(pattern, page_text, re.DOTALL)

    print(matches[0].split('\n')[1]) if matches else None
    print('----------------------------------------------------------------------')

RIO CHICO S.A.
----------------------------------------------------------------------
SM RESINAS URUGUAY SA
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
CARGILL URUGUAY S.A.
----------------------------------------------------------------------
CARGILL URUGUAY S.A.
----------------------------------------------------------------------
CARGILL URUGUAY S.A.
----------------------------------------------------------------------
CARGILL URUGUAY S.A.
----------------------------------------------------------------------
CARGILL URUGUAY S.A.
----------------------------------------------------------------------
CARGILL URUGUAY S.A.
----------------------------------------------------------------------
CARGILL URUGUAY S.A.
----------------------------------------------------------------------
TGL URUGUAY S.A.
----------------------------------------------------------------------
TGL URUGUAY S.A.
----------------------------------------------------------------------
NUTRIMAS GRANOS S.R.L
----------------------------------------------------------------------
NUTRIMAS GRANOS S.R.L
----------------------------------------------------------------------
NUTRIMAS GRANOS S.R.L
----------------------------------------------------------------------
NUTRIMAS GRANOS S.R.L
----------------------------------------------------------------------
NUTRIMAS GRANOS S.R.L
----------------------------------------------------------------------
NUTRIMAS GRANOS S.R.L
----------------------------------------------------------------------
NUTRIMAS GRANOS S.R.L
----------------------------------------------------------------------
NUTRIMAS GRANOS S.R.L
----------------------------------------------------------------------
NUTRIMAS GRANOS S.R.L
----------------------------------------------------------------------
NUTRIMAS GRANOS S.R.L
----------------------------------------------------------------------
DARCEL  S.A.
----------------------------------------------------------------------
DARCEL  S.A.
----------------------------------------------------------------------
DARCEL  S.A.
----------------------------------------------------------------------
KRAH AMERICA LATINA SA
----------------------------------------------------------------------
KRAH AMERICA LATINA SA
----------------------------------------------------------------------
KRAH AMERICA LATINA SA
----------------------------------------------------------------------
PETROQUIMICA DOW S.A.
----------------------------------------------------------------------
PETROQUIMICA DOW S.A.
----------------------------------------------------------------------
WINPACK SA
----------------------------------------------------------------------
POLYTEX S.A. (RUC: 96.777.810-9)
----------------------------------------------------------------------
POLYTEX S.A. (RUC: 96.777.810-9)
----------------------------------------------------------------------
TRANSPORTE Y LOGISTICA LIMITADA
----------------------------------------------------------------------
KRAH AMERICA LATINA SA
----------------------------------------------------------------------
KRAH AMERICA LATINA SA
----------------------------------------------------------------------
KRAH AMERICA LATINA SA
----------------------------------------------------------------------
KRAH AMERICA LATINA SA
----------------------------------------------------------------------
KRAH AMERICA LATINA SA
----------------------------------------------------------------------
POLYTEX S.A. (RUC: 96.777.810-9)
----------------------------------------------------------------------
POLYTEX S.A. (RUC: 96.777.810-9)
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
PERFIL GRANOS S.R.L.
----------------------------------------------------------------------
PERFIL GRANOS S.R.L.
----------------------------------------------------------------------
PERFIL GRANOS S.R.L.
----------------------------------------------------------------------
PERFIL GRANOS S.R.L.
----------------------------------------------------------------------
PERFIL GRANOS S.R.L.
----------------------------------------------------------------------
PERFIL GRANOS S.R.L.
----------------------------------------------------------------------
PERFIL GRANOS S.R.L.
----------------------------------------------------------------------
PERFIL GRANOS S.R.L.
----------------------------------------------------------------------
PERFIL GRANOS S.R.L.
----------------------------------------------------------------------
PERFIL GRANOS S.R.L.
----------------------------------------------------------------------
PERFIL GRANOS S.R.L.
----------------------------------------------------------------------
PERFIL GRANOS S.R.L.
----------------------------------------------------------------------
PERFIL GRANOS S.R.L.
----------------------------------------------------------------------
PERFIL GRANOS S.R.L.
----------------------------------------------------------------------
MEGAAGRO TRADING S.A.
----------------------------------------------------------------------
MEGAAGRO TRADING S.A.
----------------------------------------------------------------------
MEGAAGRO TRADING S.A.
----------------------------------------------------------------------
MEGAAGRO TRADING S.A.
----------------------------------------------------------------------
MEGAAGRO TRADING S.A.
----------------------------------------------------------------------
MEGAAGRO TRADING S.A.
----------------------------------------------------------------------
MEGAAGRO TRADING S.A.
----------------------------------------------------------------------
MEGAAGRO TRADING S.A.
----------------------------------------------------------------------
MEGAAGRO TRADING S.A.
----------------------------------------------------------------------
MEGAAGRO TRADING S.A.
----------------------------------------------------------------------
MEGAAGRO TRADING S.A.
----------------------------------------------------------------------
MEGAAGRO TRADING S.A.
----------------------------------------------------------------------
MEGAAGRO TRADING S.A.
----------------------------------------------------------------------
MEGAAGRO TRADING S.A.
----------------------------------------------------------------------
MEGAAGRO TRADING S.A.
----------------------------------------------------------------------
MEGAAGRO TRADING S.A.
----------------------------------------------------------------------
MEGAAGRO TRADING S.A.
----------------------------------------------------------------------
MEGAAGRO TRADING S.A.
----------------------------------------------------------------------
MEGAAGRO TRADING S.A.
----------------------------------------------------------------------
MEGAAGRO TRADING S.A.
----------------------------------------------------------------------
MEGAAGRO TRADING S.A.
----------------------------------------------------------------------
MEGAAGRO TRADING S.A.
----------------------------------------------------------------------
MEGAAGRO TRADING S.A.
----------------------------------------------------------------------
MEGAAGRO TRADING S.A.
----------------------------------------------------------------------
MEGAAGRO TRADING S.A.
----------------------------------------------------------------------
MEGAAGRO TRADING S.A.
----------------------------------------------------------------------
MEGAAGRO TRADING S.A.
----------------------------------------------------------------------
MEGAAGRO TRADING S.A.
----------------------------------------------------------------------
MEGAAGRO TRADING S.A.
----------------------------------------------------------------------
MEGAAGRO TRADING S.A.
----------------------------------------------------------------------
MEGAAGRO TRADING S.A.
----------------------------------------------------------------------
MEGAAGRO TRADING S.A.
----------------------------------------------------------------------
MEGAAGRO TRADING S.A.
----------------------------------------------------------------------
MEGAAGRO TRADING S.A.
----------------------------------------------------------------------
MEGAAGRO TRADING S.A.
----------------------------------------------------------------------
J.MACEDO S.A. (CNPJ 14998371/0064-00)
----------------------------------------------------------------------
J.MACEDO S.A. (CNPJ 14998371/0064-00)
----------------------------------------------------------------------
M.DIAS BRANCO S.A. INDUSTRIA E COMERCIO DE ALIMENT
----------------------------------------------------------------------
M.DIAS BRANCO S.A. INDUSTRIA E COMERCIO DE ALIMENT
----------------------------------------------------------------------
M.DIAS BRANCO S.A. INDUSTRIA E COMERCIO DE ALIMENT
----------------------------------------------------------------------
CRYOVAC LONDRINA LTDA (CNPJ 00200283000115)
----------------------------------------------------------------------
PASTIFICIO SELMI S.A. (CNPJ 46025722/0001-00)
----------------------------------------------------------------------
PASTIFICIO SELMI S.A. (CNPJ 46025722/0001-00)
----------------------------------------------------------------------
PASTIFICIO SELMI S.A. (CNPJ 46025722/0001-00)
----------------------------------------------------------------------
DARCEL  S.A.
----------------------------------------------------------------------
DARCEL  S.A.
----------------------------------------------------------------------
DARCEL  S.A.
----------------------------------------------------------------------
EXPORTCHILE LTDA (RUT 76.246.110-2)
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
RIO CHICO S.A.
----------------------------------------------------------------------
POLYTEX S.A. (RUC: 96.777.810-9)
----------------------------------------------------------------------
WINPACK S.A.
----------------------------------------------------------------------
WINPACK S.A.
----------------------------------------------------------------------
WINPACK S.A.
----------------------------------------------------------------------
EMPRESAS LIPIGAS S.A
----------------------------------------------------------------------
EMPRESAS LIPIGAS S.A

In [41]:
def get_DESTINATARIO(archivos: list[str]):
    data = []
    for archivo in archivos:
        
        pdf = fitz.open(archivo).load_page(0)
            # Load the page content as text
        page_text = pdf.get_text("text")

        #print(page_text)

        texto_antes = '/ Destinatario'
        texto_despues = '35 Consignatario /Consignatario'
        pattern = re.escape(texto_antes) + r"(.*)" + re.escape(texto_despues)
        matches = re.findall(pattern, page_text, re.DOTALL)

        data.append(matches[0].split('\n')[1] if matches else None)
    return data

get_DESTINATARIO(archivos)

['RIO CHICO S.A.',
 'SM RESINAS URUGUAY SA',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'CARGILL URUGUAY S.A.',
 'CARGILL URUGUAY S.A.',
 'CARGILL URUGUAY S.A.',
 'CARGILL URUGUAY S.A.',
 'CARGILL URUGUAY S.A.',
 'CARGILL URUGUAY S.A.',
 'CARGILL URUGUAY S.A.',
 'TGL URUGUAY S.A.',
 'TGL URUGUAY S.A.',
 'NUTRIMAS GRANOS S.R.L',
 'NUTRIMAS GRANOS S.R.L',
 'NUTRIMAS GRANOS S.R.L',
 'NUTRIMAS GRANOS S.R.L',
 'NUTRIMAS GRANOS S.R.L',
 'NUTRIMAS GRANOS S.R.L',
 'NUTRIMAS GRANOS S.R.L',
 'NUTRIMAS GRANOS S.R.L',
 'NUTRIMAS GRANOS S.R.L',
 'NUTRIMAS GRANOS S.R.L',
 'DARCEL  S.A.',
 'DARCEL  S.A.',
 'DARCEL  S.A.',
 'KRAH AMERICA LATINA SA',
 'KRAH AMERICA LATINA SA',
 'KRAH AMERICA LATINA SA',
 'PETROQUIMICA DOW S.A.',
 'PETROQUIMICA DOW S.A.',
 'WINPACK SA',
 'POLYTEX S.A. (RUC: 96.777.810-9)',
 'POLYTEX S.A. (RUC: 96.777.810-9)',
 'TRANSPORTE Y LOGISTICA LIMITADA ',
 'KRAH AMERICA LATINA SA',
 'KRAH AMERICA LATINA SA',
 'KRAH AMERICA LATINA SA',
 'KRAH AMERICA LATINA SA',
 'KRAH AMERICA LATINA SA',
 'POLYTEX S.A. (RUC: 96.777.810-9)',
 'POLYTEX S.A. (RUC: 96.777.810-9)',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'PERFIL GRANOS S.R.L.',
 'PERFIL GRANOS S.R.L.',
 'PERFIL GRANOS S.R.L.',
 'PERFIL GRANOS S.R.L.',
 'PERFIL GRANOS S.R.L.',
 'PERFIL GRANOS S.R.L.',
 'PERFIL GRANOS S.R.L.',
 'PERFIL GRANOS S.R.L.',
 'PERFIL GRANOS S.R.L.',
 'PERFIL GRANOS S.R.L.',
 'PERFIL GRANOS S.R.L.',
 'PERFIL GRANOS S.R.L.',
 'PERFIL GRANOS S.R.L.',
 'PERFIL GRANOS S.R.L.',
 'MEGAAGRO TRADING S.A.',
 'MEGAAGRO TRADING S.A.',
 'MEGAAGRO TRADING S.A.',
 'MEGAAGRO TRADING S.A.',
 'MEGAAGRO TRADING S.A.',
 'MEGAAGRO TRADING S.A.',
 'MEGAAGRO TRADING S.A.',
 'MEGAAGRO TRADING S.A.',
 'MEGAAGRO TRADING S.A.',
 'MEGAAGRO TRADING S.A.',
 'MEGAAGRO TRADING S.A.',
 'MEGAAGRO TRADING S.A.',
 'MEGAAGRO TRADING S.A.',
 'MEGAAGRO TRADING S.A.',
 'MEGAAGRO TRADING S.A.',
 'MEGAAGRO TRADING S.A.',
 'MEGAAGRO TRADING S.A.',
 'MEGAAGRO TRADING S.A.',
 'MEGAAGRO TRADING S.A.',
 'MEGAAGRO TRADING S.A.',
 'MEGAAGRO TRADING S.A.',
 'MEGAAGRO TRADING S.A.',
 'MEGAAGRO TRADING S.A.',
 'MEGAAGRO TRADING S.A.',
 'MEGAAGRO TRADING S.A.',
 'MEGAAGRO TRADING S.A.',
 'MEGAAGRO TRADING S.A.',
 'MEGAAGRO TRADING S.A.',
 'MEGAAGRO TRADING S.A.',
 'MEGAAGRO TRADING S.A.',
 'MEGAAGRO TRADING S.A.',
 'MEGAAGRO TRADING S.A.',
 'MEGAAGRO TRADING S.A.',
 'MEGAAGRO TRADING S.A.',
 'MEGAAGRO TRADING S.A.',
 'J.MACEDO S.A. (CNPJ 14998371/0064-00)',
 'J.MACEDO S.A. (CNPJ 14998371/0064-00)',
 'M.DIAS BRANCO S.A. INDUSTRIA E COMERCIO DE ALIMENT',
 'M.DIAS BRANCO S.A. INDUSTRIA E COMERCIO DE ALIMENT',
 'M.DIAS BRANCO S.A. INDUSTRIA E COMERCIO DE ALIMENT',
 'CRYOVAC LONDRINA LTDA (CNPJ 00200283000115)',
 'PASTIFICIO SELMI S.A. (CNPJ 46025722/0001-00)',
 'PASTIFICIO SELMI S.A. (CNPJ 46025722/0001-00)',
 'PASTIFICIO SELMI S.A. (CNPJ 46025722/0001-00)',
 'DARCEL  S.A.',
 'DARCEL  S.A.',
 'DARCEL  S.A.',
 'EXPORTCHILE LTDA (RUT 76.246.110-2)',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'POLYTEX S.A. (RUC: 96.777.810-9)',
 'WINPACK S.A.',
 'WINPACK S.A.',
 'WINPACK S.A.',
 'EMPRESAS LIPIGAS S.A',
 'EMPRESAS LIPIGAS S.A',
 'EMPRESAS LIPIGAS S.A',
 'EMPRESAS LIPIGAS S.A',
 'CRYOVAC LONDRINA LTDA',
 'EMPRESAS LIPIGAS S.A',
 'EMPRESAS LIPIGAS S.A',
 'EMPRESAS LIPIGAS S.A',
 'EMPRESAS LIPIGAS S.A',
 'EMPRESAS LIPIGAS S.A',
 'EMPRESAS LIPIGAS S.A',
 'EMPRESAS LIPIGAS S.A',
 'TONDO S.A. (CNPJ 88.618.285/0004-12)',
 'TONDO S.A. (CNPJ 88.618.285/0004-12)',
 'EXPORTCHILE LTDA (RUT 76.246.110-2)',
 'BUNGE CHILE SPA',
 'BUNGE CHILE SPA',
 'PASTIFICIO SELMI S.A. (CNPJ 46025722/0001-00)',
 'PASTIFICIO SELMI S.A. (CNPJ 46025722/0001-00)',
 'PASTIFICIO SELMI S.A. (CNPJ 46025722/0001-00)',
 'PASTIFICIO SELMI S.A. (CNPJ 46025722/0001-00)',
 'PASTIFICIO SELMI S.A. (CNPJ 46025722/0001-00)',
 'PASTIFICIO SELMI S.A. (CNPJ 46025722/0001-00)',
 'PASTIFICIO SELMI S.A. (CNPJ 46025722/0001-00)',
 'EXPORTCHILE LTDA (RUT 76.246.110-2)',
 'J.MACEDO S.A. (CNPJ 14998371/0064-00)',
 'J.MACEDO S.A. (CNPJ 14998371/0064-00)',
 'CAMIL ALIMENTOS (CNPJ 64904.295/0052-53)',
 'PASTIFICIO SELMI S.A. (CNPJ 46025722/0001-00)',
 'PASTIFICIO SELMI S.A. (CNPJ 46025722/0001-00)',
 'PASTIFICIO SELMI S.A. (CNPJ 46025722/0001-00)',
 'CARGILL URUGUAY S.A.',
 'CARGILL URUGUAY S.A.',
 'CARGILL URUGUAY S.A.',
 'CARGILL URUGUAY S.A.',
 'CARGILL URUGUAY S.A.',
 'CARGILL URUGUAY S.A.',
 'CARGILL URUGUAY S.A.',
 'CARGILL URUGUAY S.A.',
 'CARGILL URUGUAY S.A.',
 'CARGILL URUGUAY S.A.',
 'CARGILL URUGUAY S.A.',
 'CARGILL URUGUAY S.A.',
 'CARGILL URUGUAY S.A.',
 'CARGILL URUGUAY S.A.',
 'CARGILL URUGUAY S.A.',
 'CARGILL URUGUAY S.A.',
 'CARGILL URUGUAY S.A.',
 'PROLESA S A',
 'PROLESA S A',
 'PROLESA S A',
 'PROLESA S A',
 'PROLESA S A',
 'PROLESA S A',
 'PROLESA S A',
 'PROLESA S A',
 'PROLESA S A',
 'SUR LITERAL SAS',
 'SUR LITERAL SAS',
 'SUR LITERAL SAS',
 'SUR LITERAL SAS',
 'SUR LITERAL SAS',
 'SUR LITERAL SAS',
 'SUR LITERAL SAS',
 'SUR LITERAL SAS',
 'SUR LITERAL SAS',
 'SUR LITERAL SAS',
 'COPA ENERGIA S.A.',
 'COPA ENERGIA S.A.',
 'COPA ENERGIA S.A.',
 'TRANQUERA ORIENTAL',
 'TRANQUERA ORIENTAL',
 'TRANQUERA ORIENTAL',
 'TRANQUERA ORIENTAL',
 'TRANQUERA ORIENTAL',
 'TRANQUERA ORIENTAL',
 'TRANQUERA ORIENTAL',
 'TRANQUERA ORIENTAL',
 'TRANQUERA ORIENTAL',
 'TRANQUERA ORIENTAL',
 'PROLESA S A',
 'PASTIFICIO SELMI S.A. (CNPJ 46025722/0001-00)',
 'PASTIFICIO SELMI S.A. (CNPJ 46025722/0001-00)',
 'PASTIFICIO SELMI S.A. (CNPJ 46025722/0001-00)',
 'PASTIFICIO SELMI S.A. (CNPJ 46025722/0001-00)',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'EXPORTCHILE LTDA (RUT 76.246.110-2)',
 'TONDO S.A. (CNPJ 88.618.285/0004-12)',
 'TONDO S.A. (CNPJ 88.618.285/0004-12)',
 'J.MACEDO S.A. (CNPJ 14998371/0064-00)',
 'J.MACEDO S.A. (CNPJ 14998371/0064-00)',
 'BUNGE CHILE SPA',
 'BUNGE CHILE SPA',
 'BUNGE CHILE SPA',
 'POLYTEX S.A. (RUC: 96.777.810-9)',
 'PETROQUIMICA DOW S.A.',
 'POLYTEX S.A. (RUC: 96.777.810-9)',
 'POLYTEX S.A. (RUC: 96.777.810-9)',
 'POLYTEX S.A. (RUC: 96.777.810-9)',
 'TRANSPORTE Y LOGISTICA LIMITADA',
 'PETROQUIMICA DOW S.A.',
 'POLYTEX S.A. (RUC: 96.777.810-9)',
 'POLYTEX S.A. (RUC: 96.777.810-9)',
 'PETROQUIMICA DOW S.A.',
 'POLYTEX S.A. (RUC: 96.777.810-9)',
 'POLYTEX S.A. (RUC: 96.777.810-9)',
 'CONAPAC  SA',
 'CONAPAC  SA',
 'PLASTICOS DE LA ISLA GRANDE S.A.',
 'PLASTICOS DE LA ISLA GRANDE',
 'PLASTICOS DE LA ISLA GRANDE S.A.',
 'PLASTICOS DE LA ISLA GRANDE',
 'PLASTICOS DE LA ISLA GRANDE',
 'PLASTICOS DE LA ISLA GRANDE S.A.',
 'PLASTICOS DE LA ISLA GRANDE',
 'PLASTICOS DE LA ISLA GRANDE',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'M.DIAS BRANCO S.A. INDUSTRIA E COMERCIO DE ALIMENT',
 'M.DIAS BRANCO S.A. INDUSTRIA E COMERCIO DE ALIMENT',
 'M.DIAS BRANCO S.A. INDUSTRIA E COMERCIO DE ALIMENT',
 'M.DIAS BRANCO S.A. INDUSTRIA E COMERCIO DE ALIMENT',
 'M.DIAS BRANCO S.A. INDUSTRIA E COMERCIO DE ALIMENT',
 'M.DIAS BRANCO S.A. INDUSTRIA E COMERCIO DE ALIMENT',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'J.MACEDO S.A. (CNPJ 14998371/0064-00)',
 'J.MACEDO S.A. (CNPJ 14998371/0064-00)',
 'PASTIFICIO SELMI S.A. (CNPJ 46025722/0001-00)',
 'PASTIFICIO SELMI S.A. (CNPJ 46025722/0001-00)',
 'PASTIFICIO SELMI S.A. (CNPJ 46025722/0001-00)',
 'CONAPAC  SA',
 'CONAPAC  SA',
 'EXPORTCHILE LTDA (RUT 76.246.110-2)',
 'MASSAS ALIMENTICIAS DA ROZ LTDA ',
 'EXPORTCHILE LTDA (RUT 76.246.110-2)',
 'POLYTEX S.A. (RUC: 96.777.810-9)',
 'NETAFIM CHILE LIMITADA (RUT: 76.241.360-4)',
 'NETAFIM CHILE LIMITADA (RUT: 76.241.360-4)',
 'POLYTEX S.A. (RUC: 96.777.810-9)',
 'KRAH AMERICA LATINA SA',
 'POLYTEX S.A. (RUC: 96.777.810-9)',
 'CONAPAC S.A.',
 'COPA ENERGIA S.A.',
 'COPA ENERGIA S.A.',
 'COPA ENERGIA S.A.',
 'AIROS LTDA',
 'AIROS LTDA',
 'AIROS LTDA',
 'AIROS LTDA',
 'AIROS LTDA',
 'PETROQUIM S.R.L. - NIT 1030383029',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'PASTIFICIO SELMI S.A. (CNPJ 46025722/0001-00)',
 'PASTIFICIO SELMI S.A. (CNPJ 46025722/0001-00)',
 'PASTIFICIO SELMI S.A. (CNPJ 46025722/0001-00)',
 'ELEMENTA FOODS CHILE S.A.',
 'ELEMENTA FOODS CHILE S.A.',
 'KRAH AMERICA LATINA SA',
 'KRAH AMERICA LATINA SA',
 'KRAH AMERICA LATINA SA',
 'KRAH AMERICA LATINA SA',
 'POLYTEX S.A. (RUC: 96.777.810-9)',
 'KRAH AMERICA LATINA SA',
 'KRAH AMERICA LATINA SA',
 'KRAH AMERICA LATINA SA',
 'PETROQUIMICA DOW S.A.',
 'SM RESINAS URUGUAY SA -',
 'DOMINGOS COSTA INDUSTRIAS ALIMENTICIAS S.A.',
 'DARCEL  S.A.',
 'DARCEL  S.A.',
 'DARCEL  S.A.',
 'JPA LTDA.',
 'JPA LTDA.',
 'JPA LTDA.',
 'JPA LTDA.',
 'RIO CHICO S.A.',
 'TONDO S.A. (CNPJ 88.618.285/0004-12)',
 'TONDO S.A. (CNPJ 88.618.285/0004-12)',
 'LABREZZA S.A. - RUT 215404560017',
 'UNIPAR INDUPA DO BRASIL S.A.',
 'DOMINGOS COSTA INDUSTRIAS ALIMENTICIAS S.A.',
 'EXPORTCHILE LTDA (RUT 76.246.110-2)',
 'CARGILL URUGUAY S.A.',
 'CARGILL URUGUAY S.A.',
 'CARGILL URUGUAY S.A.',
 'CARGILL URUGUAY S.A.',
 'CARGILL URUGUAY S.A.',
 'CARGILL URUGUAY S.A.',
 'CARGILL URUGUAY S.A.',
 'CARGILL URUGUAY S.A.',
 'CARGILL URUGUAY S.A.',
 'CARGILL URUGUAY S.A.',
 'CARGILL URUGUAY S.A.',
 'CARGILL URUGUAY S.A.',
 'CARGILL URUGUAY S.A.',
 'CARGILL URUGUAY S.A.',
 'CARGILL URUGUAY S.A.',
 'CARGILL URUGUAY S.A.',
 'NUTRIMAS GRANOS S.R.L',
 'EMPRESAS LIPIGAS S.A.',
 'EMPRESAS LIPIGAS S.A',
 'EMPRESAS LIPIGAS S.A',
 'EMPRESAS LIPIGAS S.A.',
 'EMPRESAS LIPIGAS S.A',
 'EMPRESAS LIPIGAS S.A',
 'EMPRESAS LIPIGAS S.A.',
 'EMPRESAS LIPIGAS S.A',
 'KRAH AMERICA LATINA SA',
 'KRAH AMERICA LATINA SA',
 'KRAH AMERICA LATINA SA',
 'KRAH AMERICA LATINA SA',
 'KRAH AMERICA LATINA SA',
 'POLYTEX SA ( RUT: 96.777.810-9)',
 'POLYTEX S.A. (RUC: 96.777.810-9)',
 'POLYTEX S.A. (RUC: 96.777.810-9)',
 'POLYTEX S.A. (RUC: 96.777.810-9)',
 'POLYTEX S.A. (RUC: 96.777.810-9)',
 'KRAH AMERICA LATINA SA',
 'KRAH AMERICA LATINA SA',
 'KRAH AMERICA LATINA SA',
 'WINPACK S.A.',
 'SM RESINAS URUGUAY SA',
 'SM RESINAS URUGUAY SA',
 'SM RESINAS URUGUAY SA',
 'TASHIRO Y TAKATA S.A.',
 'SM RESINAS URUGUAY SA -',
 'PASTIFICIO SELMI S.A. (CNPJ 46025722/0001-00)',
 'PASTIFICIO SELMI S.A. (CNPJ 46025722/0001-00)',
 'PASTIFICIO SELMI S.A. (CNPJ 46025722/0001-00)',
 'DARCEL  S.A.',
 'DARCEL  S.A.',
 'DARCEL  S.A.',
 'INAL LTDA (RUT 77.844.340-6)',
 'PROLESA S A',
 'PROLESA S A',
 'PROLESA S A',
 'PROLESA S A',
 'PROLESA S A',
 'TRANQUERA ORIENTAL',
 'TRANQUERA ORIENTAL',
 'TRANQUERA ORIENTAL S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'RIO CHICO S.A.',
 'UNIPAR INDUPA BR SA',
 'UNIPAR INDUPA BR SA',
 'UNIPAR INDUPA BR SA',
 'UNIPAR INDUPA BR SA',
 'MOINHO  ARAPONGAS  S.A. (76.125.244/0001-62)',
 'MOINHO  ARAPONGAS  S.A. (76.125.244/0001-62)',
 'J.MACEDO S.A. (CNPJ 14998371/0064-00)',
 'J.MACEDO S.A. (CNPJ 14998371/0064-00)',
 'PASTIFICIO SELMI S.A. (CNPJ 46025722/0001-00)',
 'PASTIFICIO SELMI S.A. (CNPJ 46025722/0001-00)',
 'PASTIFICIO SELMI S.A. (CNPJ 46025722/0001-00)',
 'J.MACEDO S.A. (CNPJ 14998371/0064-00)',
 'J.MACEDO S.A. (CNPJ 14998371/0064-00)',
 'MEGAAGRO TRADING S.A.',
 'MEGAAGRO TRADING S.A.',
 'MEGAAGRO TRADING S.A.',
 'SM RESINAS URUGUAY SA -',
 'SM RESINAS URUGUAY SA',
 'INPLASUL INDUSTRIA DE PLASTICOS',
 'INPLASUL INDUSTRIA DE PLASTICOS',
 'INPLASUL INDUSTRIA DE PLASTICOS',
 'INPLASUL INDUSTRIA DE PLASTICOS',
 'INPLASUL INDUSTRIA DE PLASTICOS',
 'INPLASUL INDUSTRIA DE PLASTICOS',
 'INPLASUL INDUSTRIA DE PLASTICOS',
 'INPLASUL INDUSTRIA DE PLASTICOS',
 'INPLASUL INDUSTRIA DE PLASTICOS',
 'INPLASUL INDUSTRIA DE PLASTICOS',
 'SM RESINAS BRASIL LTDA (CNPJ 04.728.228/0003-15)',
 'SM RESINAS BRASIL LTDA (CNPJ 04.728.228/0003-15)',
 'SM RESINAS BRASIL LTDA (CNPJ 04.728.228/0003-15)',
 'SM RESINAS BRASIL LTDA (CNPJ 04.728.228/0003-15)',
 'SM RESINAS BRASIL LTDA (CNPJ 04.728.228/0003-15)',
 'EXPORTCHILE LTDA (RUT 76.246.110-2)',
 'TKS COMERCIO IMPORTAC?O E EXPORTAC?O LTDA',
 'J.MACEDO S.A. (CNPJ 14998371/0064-00)',
 'J.MACEDO S.A. (CNPJ 14998371/0064-00)',
 'TONDO S.A. (CNPJ 88.618.285/0004-12)',
 'TONDO S.A. (CNPJ 88.618.285/0004-12)']

In [42]:
def check_format(pdf: PDFQuery):
    """
    Verifica si el formato del PDF es correcto.


    Args:
        pdf (PDFQuery): instancia de PDFQuery del archivo PDF.
    """
    try:
        val = bool(pdf.pq('LTTextLineHorizontal:contains("Manifiesto Internacional de Carga por Carretera / Declaracion de Transito Aduanero")'))
        return val
    except Exception as e:
        raise ValueError(f"Error al verificar el formato del PDF: {e}")
    
pdf = PDFQuery(archivos[0])
pdf.load(0)    
check_format(pdf)

True

In [ ]:
df = pd.read_excel('data/DATAAAANEWLAST.xlsx')

#df['PRODUCTO'] = #LOGICA EN BASE AL EXPORTADOR
    
    #SI EL EXPORTADOR ES	LA MERCADERIA ES
    #PBBPOLISUR SOCIEDAD DE RESPONS	POLIETILENO
    #UNIPAR INDUPA SAIC	POLICLORURO DE VINILO
    #COMPA?IA MEGA SOCIEDAD ANONIMA	GAS LICUADO
    #COMPA?IA MOLINERA DEL SUR S. A	SEMOLA DE TRIGO
    #TRANSPORTADORA DE GAS DEL SUR	GAS LICUADO
    #VITERRA ARGENTINA S.A.	ACEITE / PELLETS / LECITINA
    #LA NUEVA MANERA S.A.	HARINA DE TRIGO
    #SYNGENTA	ACEITE
    #SI NO CUMPLE CON LAS ANTERIORES	INDETERMINADO
    
def logica_PRODUCTO():
    pass

df

In [43]:
def get_EXPORTADOR(pdf: PDFQuery):
    text  =  pdf.pq('LTTextLineHorizontal:contains("/ Remetente")').next().text()
    return text

In [45]:
data = []
for archivo in archivos:
    pdf = PDFQuery(archivo)
    pdf.load(0)
    exportador = (get_EXPORTADOR(pdf))
    print(exportador)
    data.append(exportador)

PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
COMPA?IA MOLINERA DEL SUR S. A
COMPA?IA MOLINERA DEL SUR S. A
COMPA?IA MOLINERA DEL SUR S. A
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
CALLE 42 1253 - ROMANG (3555)
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
COMPA?IA MOLINERA DEL SUR S. A
COMPA?IA MOLINERA DEL SUR S. A
COMPA?IA MOLINERA DEL SUR S. A
COMPA?IA MOLINERA DEL SUR S. A
COMPA?IA MOLINERA DEL SUR S. A
PBBPOLISUR SOCIEDAD DE RESPONS
COMPA?IA MOLINERA DEL SUR S. A
COMPA?IA MOLINERA DEL SUR S. A
COMPA?IA MOLINERA DEL SUR S. A
COMPA?IA MOLINERA DEL SUR S. A
COMPA?IA MOLINERA DEL SUR S. A
COMPA?IA MOLINERA DEL SUR S. A
COMPA?IA MOLINERA DEL SUR S. A
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
COMPA?IA MEGA SOCIEDAD ANONIMA
COMPA?IA MEGA SOCIEDAD ANONIMA
COMPA?IA MEGA SOCIEDAD ANONIMA
COMPA?IA MEGA SOCIEDAD ANONIMA
PBBPOLISUR SOCIEDAD DE RESPONS
COMPA?IA MEGA SOCIEDAD ANONIMA
COMPA?IA MEGA SOCIEDAD ANONIMA
COMPA?IA MEGA SOCIEDAD ANONIMA
COMPA?IA MEGA SOCIEDAD ANONIMA
COMPA?IA MEGA SOCIEDAD ANONIMA
COMPA?IA MEGA SOCIEDAD ANONIMA
COMPA?IA MEGA SOCIEDAD ANONIMA
COMPA?IA MOLINERA DEL SUR S. A
COMPA?IA MOLINERA DEL SUR S. A
COMPA?IA MOLINERA DEL SUR S. A
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
COMPA?IA MOLINERA DEL SUR S. A
COMPA?IA MOLINERA DEL SUR S. A
COMPA?IA MOLINERA DEL SUR S. A
COMPA?IA MOLINERA DEL SUR S. A
COMPA?IA MOLINERA DEL SUR S. A
COMPA?IA MOLINERA DEL SUR S. A
COMPA?IA MOLINERA DEL SUR S. A
COMPA?IA MOLINERA DEL SUR S. A
COMPA?IA MOLINERA DEL SUR S. A
COMPA?IA MOLINERA DEL SUR S. A
COMPA?IA MOLINERA DEL SUR S. A
COMPA?IA MOLINERA DEL SUR S. A
COMPA?IA MOLINERA DEL SUR S. A
COMPA?IA MOLINERA DEL SUR S. A
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
TRANSPORTADORA DE GAS DEL SUR
TRANSPORTADORA DE GAS DEL SUR
TRANSPORTADORA DE GAS DEL SUR
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
COMPA?IA MOLINERA DEL SUR S. A
COMPA?IA MOLINERA DEL SUR S. A
COMPA?IA MOLINERA DEL SUR S. A
COMPA?IA MOLINERA DEL SUR S. A
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
COMPA?IA MOLINERA DEL SUR S. A
COMPA?IA MOLINERA DEL SUR S. A
COMPA?IA MOLINERA DEL SUR S. A
COMPA?IA MOLINERA DEL SUR S. A
COMPA?IA MOLINERA DEL SUR S. A
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
COMPA?IA MOLINERA DEL SUR S. A
COMPA?IA MOLINERA DEL SUR S. A
COMPA?IA MOLINERA DEL SUR S. A
COMPA?IA MOLINERA DEL SUR S. A
COMPA?IA MOLINERA DEL SUR S. A
COMPA?IA MOLINERA DEL SUR S. A
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
COMPA?IA MOLINERA DEL SUR S. A
COMPA?IA MOLINERA DEL SUR S. A
COMPA?IA MOLINERA DEL SUR S. A
COMPA?IA MOLINERA DEL SUR S. A
COMPA?IA MOLINERA DEL SUR S. A
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
COMPA?IA MOLINERA DEL SUR S. A
COMPA?IA MOLINERA DEL SUR S. A
COMPA?IA MOLINERA DEL SUR S. A
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
TRANSPORTADORA DE GAS DEL SUR
TRANSPORTADORA DE GAS DEL SUR
TRANSPORTADORA DE GAS DEL SUR
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
UNIPAR INDUPA SAIC
JUANA MANSO 555, PISO 7 D C1107CBK - CIUDAD AUTONOMA DE BUENOS AIRES,
ARGENTINA
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
COMPA?IA MOLINERA DEL SUR S. A
COMPA?IA MOLINERA DEL SUR S. A
COMPA?IA MOLINERA DEL SUR S. A
INDUSTRIAS GRINDOIL S.A.
AV RICARDO FUERTES S/N 0 - CORONEL DORREGO - BS AS - ARGENTINA (CUIT:
30716155265)
INDUSTRIAS GRINDOIL S.A.
AV RICARDO FUERTES S/N 0 - CORONEL DORREGO - BS AS - ARGENTINA (CUIT:
30716155265)
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
PBBPOLISUR SOCIEDAD DE RESPONS
COMPA?IA MOLINERA DEL SUR S. A
COMPA?IA MOLINERA DEL SUR S. A
COMPA?IA MOLINERA DEL SUR S. A
COMPA?IA MOLINERA DEL SUR S. A
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
PBBPOLISUR SOCIEDAD DE RESPONS
COMPA?IA MOLINERA DEL SUR S. A
COMPA?IA MOLINERA DEL SUR S. A
COMPA?IA MOLINERA DEL SUR S. A
UNIPAR INDUPA SAIC
JUANA MANSO 555, PISO 7 D C1107CBK - CIUDAD AUTONOMA DE BUENOS AIRES,
ARGENTINA (CUIT: 30-50215081-9)
COMPA?IA MOLINERA DEL SUR S. A
COMPA?IA MOLINERA DEL SUR S. A
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA
BUNGE ARGENTINA S. A.
25 DE MAYO 501 - CP 1002 BUENOS AIRES - ARGENTINA

In [46]:
archivo = archivos[0]
pdf = PDFQuery(archivo)
pdf.load(0)
get_NACIONALIDAD_TRANSPORTE()

NameError: name 'get_NACIONALIDAD_TRANSPORTE' is not defined

In [47]:
import pandas as pd

df = pd.DataFrame({'EXPORTADOR':data})
df['EXPORTADOR'] = df['EXPORTADOR'].str.split('\n').str[0]
df

                         EXPORTADOR
0    PBBPOLISUR SOCIEDAD DE RESPONS
1    PBBPOLISUR SOCIEDAD DE RESPONS
2    PBBPOLISUR SOCIEDAD DE RESPONS
3    PBBPOLISUR SOCIEDAD DE RESPONS
4    PBBPOLISUR SOCIEDAD DE RESPONS
5    PBBPOLISUR SOCIEDAD DE RESPONS
6    PBBPOLISUR SOCIEDAD DE RESPONS
7    PBBPOLISUR SOCIEDAD DE RESPONS
8    PBBPOLISUR SOCIEDAD DE RESPONS
9    PBBPOLISUR SOCIEDAD DE RESPONS
10   PBBPOLISUR SOCIEDAD DE RESPONS
11   PBBPOLISUR SOCIEDAD DE RESPONS
12   PBBPOLISUR SOCIEDAD DE RESPONS
13   PBBPOLISUR SOCIEDAD DE RESPONS
14   PBBPOLISUR SOCIEDAD DE RESPONS
15   PBBPOLISUR SOCIEDAD DE RESPONS
16   PBBPOLISUR SOCIEDAD DE RESPONS
17   PBBPOLISUR SOCIEDAD DE RESPONS
18   PBBPOLISUR SOCIEDAD DE RESPONS
19   PBBPOLISUR SOCIEDAD DE RESPONS
20   PBBPOLISUR SOCIEDAD DE RESPONS
21   PBBPOLISUR SOCIEDAD DE RESPONS
22   PBBPOLISUR SOCIEDAD DE RESPONS
23   PBBPOLISUR SOCIEDAD DE RESPONS
24   PBBPOLISUR SOCIEDAD DE RESPONS
25   PBBPOLISUR SOCIEDAD DE RESPONS
26            BUNGE ARGENTINA S. A.
27            BUNGE ARGENTINA S. A.
28            BUNGE ARGENTINA S. A.
29            BUNGE ARGENTINA S. A.
30            BUNGE ARGENTINA S. A.
31            BUNGE ARGENTINA S. A.
32            BUNGE ARGENTINA S. A.
33            BUNGE ARGENTINA S. A.
34            BUNGE ARGENTINA S. A.
35            BUNGE ARGENTINA S. A.
36            BUNGE ARGENTINA S. A.
37            BUNGE ARGENTINA S. A.
38            BUNGE ARGENTINA S. A.
39            BUNGE ARGENTINA S. A.
40            BUNGE ARGENTINA S. A.
41            BUNGE ARGENTINA S. A.
42            BUNGE ARGENTINA S. A.
43            BUNGE ARGENTINA S. A.
44            BUNGE ARGENTINA S. A.
45   COMPA?IA MOLINERA DEL SUR S. A
46   COMPA?IA MOLINERA DEL SUR S. A
47   COMPA?IA MOLINERA DEL SUR S. A
48   PBBPOLISUR SOCIEDAD DE RESPONS
49   PBBPOLISUR SOCIEDAD DE RESPONS
50   PBBPOLISUR SOCIEDAD DE RESPONS
51   PBBPOLISUR SOCIEDAD DE RESPONS
52   PBBPOLISUR SOCIEDAD DE RESPONS
53   PBBPOLISUR SOCIEDAD DE RESPONS
54   PBBPOLISUR SOCIEDAD DE RESPONS
55   PBBPOLISUR SOCIEDAD DE RESPONS
56   PBBPOLISUR SOCIEDAD DE RESPONS
57   PBBPOLISUR SOCIEDAD DE RESPONS
58   PBBPOLISUR SOCIEDAD DE RESPONS
59   PBBPOLISUR SOCIEDAD DE RESPONS
60   PBBPOLISUR SOCIEDAD DE RESPONS
61   PBBPOLISUR SOCIEDAD DE RESPONS
62   PBBPOLISUR SOCIEDAD DE RESPONS
63   PBBPOLISUR SOCIEDAD DE RESPONS
64   PBBPOLISUR SOCIEDAD DE RESPONS
65   PBBPOLISUR SOCIEDAD DE RESPONS
66   PBBPOLISUR SOCIEDAD DE RESPONS
67   PBBPOLISUR SOCIEDAD DE RESPONS
68   PBBPOLISUR SOCIEDAD DE RESPONS
69   PBBPOLISUR SOCIEDAD DE RESPONS
70   PBBPOLISUR SOCIEDAD DE RESPONS
71   PBBPOLISUR SOCIEDAD DE RESPONS
72   PBBPOLISUR SOCIEDAD DE RESPONS
73   PBBPOLISUR SOCIEDAD DE RESPONS
74   PBBPOLISUR SOCIEDAD DE RESPONS
75   PBBPOLISUR SOCIEDAD DE RESPONS
76   PBBPOLISUR SOCIEDAD DE RESPONS
77   PBBPOLISUR SOCIEDAD DE RESPONS
78   PBBPOLISUR SOCIEDAD DE RESPONS
79   PBBPOLISUR SOCIEDAD DE RESPONS
80   PBBPOLISUR SOCIEDAD DE RESPONS
81   PBBPOLISUR SOCIEDAD DE RESPONS
82   PBBPOLISUR SOCIEDAD DE RESPONS
83   PBBPOLISUR SOCIEDAD DE RESPONS
84   PBBPOLISUR SOCIEDAD DE RESPONS
85   PBBPOLISUR SOCIEDAD DE RESPONS
86   PBBPOLISUR SOCIEDAD DE RESPONS
87   PBBPOLISUR SOCIEDAD DE RESPONS
88   PBBPOLISUR SOCIEDAD DE RESPONS
89   PBBPOLISUR SOCIEDAD DE RESPONS
90   PBBPOLISUR SOCIEDAD DE RESPONS
91   PBBPOLISUR SOCIEDAD DE RESPONS
92   PBBPOLISUR SOCIEDAD DE RESPONS
93   PBBPOLISUR SOCIEDAD DE RESPONS
94   PBBPOLISUR SOCIEDAD DE RESPONS
95   PBBPOLISUR SOCIEDAD DE RESPONS
96   PBBPOLISUR SOCIEDAD DE RESPONS
97   PBBPOLISUR SOCIEDAD DE RESPONS
98   PBBPOLISUR SOCIEDAD DE RESPONS
99   PBBPOLISUR SOCIEDAD DE RESPONS
100  PBBPOLISUR SOCIEDAD DE RESPONS
101  PBBPOLISUR SOCIEDAD DE RESPONS
102  PBBPOLISUR SOCIEDAD DE RESPONS
103  PBBPOLISUR SOCIEDAD DE RESPONS
104  PBBPOLISUR SOCIEDAD DE RESPONS
105  PBBPOLISUR SOCIEDAD DE RESPONS
106  PBBPOLISUR SOCIEDAD DE RESPONS
107  PBBPOLISUR SOCIEDAD DE RESPONS
108  PBBPOLISUR SOCIEDAD DE RESPONS
109  PBBPOLISUR SOCIEDAD DE RESPONS
110  PBBPOLISUR SOCIEDAD DE RESPONS
111  PBBPOLISUR SOCIEDAD DE RESPONS
112  PBBPOLISUR SOCIEDAD DE RESPONS
113  PBBPOLISUR SOCIEDAD DE RESPONS
114  PBBPOLISUR SOCIEDAD DE RESPONS
115  PBBPOLISUR SOCIEDAD DE RESPONS
116  PBBPOLISUR SOCIEDAD DE RESPONS
117  PBBPOLISUR SOCIEDAD DE RESPONS
118  PBBPOLISUR SOCIEDAD DE RESPONS
119  PBBPOLISUR SOCIEDAD DE RESPONS
120  PBBPOLISUR SOCIEDAD DE RESPONS
121  PBBPOLISUR SOCIEDAD DE RESPONS
122  PBBPOLISUR SOCIEDAD DE RESPONS
123  PBBPOLISUR SOCIEDAD DE RESPONS
124           BUNGE ARGENTINA S. A.
125           BUNGE ARGENTINA S. A.
126           BUNGE ARGENTINA S. A.
127           BUNGE ARGENTINA S. A.
128           BUNGE ARGENTINA S. A.
129           BUNGE ARGENTINA S. A.
130           BUNGE ARGENTINA S. A.
131           BUNGE ARGENTINA S. A.
132           BUNGE ARGENTINA S. A.
133           BUNGE ARGENTINA S. A.
134           BUNGE ARGENTINA S. A.
135           BUNGE ARGENTINA S. A.
136           BUNGE ARGENTINA S. A.
137           BUNGE ARGENTINA S. A.
138           BUNGE ARGENTINA S. A.
139           BUNGE ARGENTINA S. A.
140           BUNGE ARGENTINA S. A.
141           BUNGE ARGENTINA S. A.
142           BUNGE ARGENTINA S. A.
143           BUNGE ARGENTINA S. A.
144           BUNGE ARGENTINA S. A.
145           BUNGE ARGENTINA S. A.
146           BUNGE ARGENTINA S. A.
147           BUNGE ARGENTINA S. A.
148           BUNGE ARGENTINA S. A.
149           BUNGE ARGENTINA S. A.
150           BUNGE ARGENTINA S. A.
151           BUNGE ARGENTINA S. A.
152           BUNGE ARGENTINA S. A.
153           BUNGE ARGENTINA S. A.
154           BUNGE ARGENTINA S. A.
155           BUNGE ARGENTINA S. A.
156           BUNGE ARGENTINA S. A.
157           BUNGE ARGENTINA S. A.
158           BUNGE ARGENTINA S. A.
159           BUNGE ARGENTINA S. A.
160           BUNGE ARGENTINA S. A.
161           BUNGE ARGENTINA S. A.
162           BUNGE ARGENTINA S. A.
163           BUNGE ARGENTINA S. A.
164           BUNGE ARGENTINA S. A.
165           BUNGE ARGENTINA S. A.
166           BUNGE ARGENTINA S. A.
167           BUNGE ARGENTINA S. A.
168           BUNGE ARGENTINA S. A.
169           BUNGE ARGENTINA S. A.
170           BUNGE ARGENTINA S. A.
171           BUNGE ARGENTINA S. A.
172           BUNGE ARGENTINA S. A.
173  COMPA?IA MOLINERA DEL SUR S. A
174  COMPA?IA MOLINERA DEL SUR S. A
175  COMPA?IA MOLINERA DEL SUR S. A
176  COMPA?IA MOLINERA DEL SUR S. A
177  COMPA?IA MOLINERA DEL SUR S. A
178  PBBPOLISUR SOCIEDAD DE RESPONS
179  COMPA?IA MOLINERA DEL SUR S. A
180  COMPA?IA MOLINERA DEL SUR S. A
181  COMPA?IA MOLINERA DEL SUR S. A
182  COMPA?IA MOLINERA DEL SUR S. A
183  COMPA?IA MOLINERA DEL SUR S. A
184  COMPA?IA MOLINERA DEL SUR S. A
185  COMPA?IA MOLINERA DEL SUR S. A
186  PBBPOLISUR SOCIEDAD DE RESPONS
187  PBBPOLISUR SOCIEDAD DE RESPONS
188  PBBPOLISUR SOCIEDAD DE RESPONS
189  PBBPOLISUR SOCIEDAD DE RESPONS
190  PBBPOLISUR SOCIEDAD DE RESPONS
191  PBBPOLISUR SOCIEDAD DE RESPONS
192  PBBPOLISUR SOCIEDAD DE RESPONS
193  PBBPOLISUR SOCIEDAD DE RESPONS
194  PBBPOLISUR SOCIEDAD DE RESPONS
195  PBBPOLISUR SOCIEDAD DE RESPONS
196  PBBPOLISUR SOCIEDAD DE RESPONS
197  PBBPOLISUR SOCIEDAD DE RESPONS
198  PBBPOLISUR SOCIEDAD DE RESPONS
199  PBBPOLISUR SOCIEDAD DE RESPONS
200  PBBPOLISUR SOCIEDAD DE RESPONS
201  PBBPOLISUR SOCIEDAD DE RESPONS
202  PBBPOLISUR SOCIEDAD DE RESPONS
203  PBBPOLISUR SOCIEDAD DE RESPONS
204  PBBPOLISUR SOCIEDAD DE RESPONS
205  PBBPOLISUR SOCIEDAD DE RESPONS
206  PBBPOLISUR SOCIEDAD DE RESPONS
207  PBBPOLISUR SOCIEDAD DE RESPONS
208  PBBPOLISUR SOCIEDAD DE RESPONS
209  PBBPOLISUR SOCIEDAD DE RESPONS
210  PBBPOLISUR SOCIEDAD DE RESPONS
211  PBBPOLISUR SOCIEDAD DE RESPONS
212  PBBPOLISUR SOCIEDAD DE RESPONS
213  PBBPOLISUR SOCIEDAD DE RESPONS
214  PBBPOLISUR SOCIEDAD DE RESPONS
215  PBBPOLISUR SOCIEDAD DE RESPONS
216  PBBPOLISUR SOCIEDAD DE RESPONS
217  PBBPOLISUR SOCIEDAD DE RESPONS
218  PBBPOLISUR SOCIEDAD DE RESPONS
219  PBBPOLISUR SOCIEDAD DE RESPONS
220  COMPA?IA MEGA SOCIEDAD ANONIMA
221  COMPA?IA MEGA SOCIEDAD ANONIMA
222  COMPA?IA MEGA SOCIEDAD ANONIMA
223  COMPA?IA MEGA SOCIEDAD ANONIMA
224  PBBPOLISUR SOCIEDAD DE RESPONS
225  COMPA?IA MEGA SOCIEDAD ANONIMA
226  COMPA?IA MEGA SOCIEDAD ANONIMA
227  COMPA?IA MEGA SOCIEDAD ANONIMA
228  COMPA?IA MEGA SOCIEDAD ANONIMA
229  COMPA?IA MEGA SOCIEDAD ANONIMA
230  COMPA?IA MEGA SOCIEDAD ANONIMA
231  COMPA?IA MEGA SOCIEDAD ANONIMA
232  COMPA?IA MOLINERA DEL SUR S. A
233  COMPA?IA MOLINERA DEL SUR S. A
234  COMPA?IA MOLINERA DEL SUR S. A
235           BUNGE ARGENTINA S. A.
236           BUNGE ARGENTINA S. A.
237  COMPA?IA MOLINERA DEL SUR S. A
238  COMPA?IA MOLINERA DEL SUR S. A
239  COMPA?IA MOLINERA DEL SUR S. A
240  COMPA?IA MOLINERA DEL SUR S. A
241  COMPA?IA MOLINERA DEL SUR S. A
242  COMPA?IA MOLINERA DEL SUR S. A
243  COMPA?IA MOLINERA DEL SUR S. A
244  COMPA?IA MOLINERA DEL SUR S. A
245  COMPA?IA MOLINERA DEL SUR S. A
246  COMPA?IA MOLINERA DEL SUR S. A
247  COMPA?IA MOLINERA DEL SUR S. A
248  COMPA?IA MOLINERA DEL SUR S. A
249  COMPA?IA MOLINERA DEL SUR S. A
250  COMPA?IA MOLINERA DEL SUR S. A
251           BUNGE ARGENTINA S. A.
252           BUNGE ARGENTINA S. A.
253           BUNGE ARGENTINA S. A.
254           BUNGE ARGENTINA S. A.
255           BUNGE ARGENTINA S. A.
256           BUNGE ARGENTINA S. A.
257           BUNGE ARGENTINA S. A.
258           BUNGE ARGENTINA S. A.
259           BUNGE ARGENTINA S. A.
260           BUNGE ARGENTINA S. A.
261           BUNGE ARGENTINA S. A.
262           BUNGE ARGENTINA S. A.
263           BUNGE ARGENTINA S. A.
264           BUNGE ARGENTINA S. A.
265           BUNGE ARGENTINA S. A.
266           BUNGE ARGENTINA S. A.
267           BUNGE ARGENTINA S. A.
268           BUNGE ARGENTINA S. A.
269           BUNGE ARGENTINA S. A.
270           BUNGE ARGENTINA S. A.
271           BUNGE ARGENTINA S. A.
272           BUNGE ARGENTINA S. A.
273           BUNGE ARGENTINA S. A.
274           BUNGE ARGENTINA S. A.
275           BUNGE ARGENTINA S. A.
276           BUNGE ARGENTINA S. A.
277           BUNGE ARGENTINA S. A.
278           BUNGE ARGENTINA S. A.
279           BUNGE ARGENTINA S. A.
280           BUNGE ARGENTINA S. A.
281           BUNGE ARGENTINA S. A.
282           BUNGE ARGENTINA S. A.
283           BUNGE ARGENTINA S. A.
284           BUNGE ARGENTINA S. A.
285           BUNGE ARGENTINA S. A.
286           BUNGE ARGENTINA S. A.
287   TRANSPORTADORA DE GAS DEL SUR
288   TRANSPORTADORA DE GAS DEL SUR
289   TRANSPORTADORA DE GAS DEL SUR
290           BUNGE ARGENTINA S. A.
291           BUNGE ARGENTINA S. A.
292           BUNGE ARGENTINA S. A.
293           BUNGE ARGENTINA S. A.
294           BUNGE ARGENTINA S. A.
295           BUNGE ARGENTINA S. A.
296           BUNGE ARGENTINA S. A.
297           BUNGE ARGENTINA S. A.
298           BUNGE ARGENTINA S. A.
299           BUNGE ARGENTINA S. A.
300           BUNGE ARGENTINA S. A.
301  COMPA?IA MOLINERA DEL SUR S. A
302  COMPA?IA MOLINERA DEL SUR S. A
303  COMPA?IA MOLINERA DEL SUR S. A
304  COMPA?IA MOLINERA DEL SUR S. A
305  PBBPOLISUR SOCIEDAD DE RESPONS
306  PBBPOLISUR SOCIEDAD DE RESPONS
307  PBBPOLISUR SOCIEDAD DE RESPONS
308  PBBPOLISUR SOCIEDAD DE RESPONS
309  PBBPOLISUR SOCIEDAD DE RESPONS
310  PBBPOLISUR SOCIEDAD DE RESPONS
311  PBBPOLISUR SOCIEDAD DE RESPONS
312  PBBPOLISUR SOCIEDAD DE RESPONS
313  PBBPOLISUR SOCIEDAD DE RESPONS
314  PBBPOLISUR SOCIEDAD DE RESPONS
315  PBBPOLISUR SOCIEDAD DE RESPONS
316  PBBPOLISUR SOCIEDAD DE RESPONS
317  PBBPOLISUR SOCIEDAD DE RESPONS
318  PBBPOLISUR SOCIEDAD DE RESPONS
319  PBBPOLISUR SOCIEDAD DE RESPONS
320  PBBPOLISUR SOCIEDAD DE RESPONS
321  PBBPOLISUR SOCIEDAD DE RESPONS
322  PBBPOLISUR SOCIEDAD DE RESPONS
323  PBBPOLISUR SOCIEDAD DE RESPONS
324  PBBPOLISUR SOCIEDAD DE RESPONS
325  COMPA?IA MOLINERA DEL SUR S. A
326  COMPA?IA MOLINERA DEL SUR S. A
327  COMPA?IA MOLINERA DEL SUR S. A
328  COMPA?IA MOLINERA DEL SUR S. A
329  COMPA?IA MOLINERA DEL SUR S. A
330           BUNGE ARGENTINA S. A.
331           BUNGE ARGENTINA S. A.
332           BUNGE ARGENTINA S. A.
333  PBBPOLISUR SOCIEDAD DE RESPONS
334  PBBPOLISUR SOCIEDAD DE RESPONS
335  PBBPOLISUR SOCIEDAD DE RESPONS
336  PBBPOLISUR SOCIEDAD DE RESPONS
337  PBBPOLISUR SOCIEDAD DE RESPONS
338  PBBPOLISUR SOCIEDAD DE RESPONS
339  PBBPOLISUR SOCIEDAD DE RESPONS
340  PBBPOLISUR SOCIEDAD DE RESPONS
341  PBBPOLISUR SOCIEDAD DE RESPONS
342  PBBPOLISUR SOCIEDAD DE RESPONS
343  PBBPOLISUR SOCIEDAD DE RESPONS
344  PBBPOLISUR SOCIEDAD DE RESPONS
345  PBBPOLISUR SOCIEDAD DE RESPONS
346  PBBPOLISUR SOCIEDAD DE RESPONS
347  PBBPOLISUR SOCIEDAD DE RESPONS
348  PBBPOLISUR SOCIEDAD DE RESPONS
349  PBBPOLISUR SOCIEDAD DE RESPONS
350  PBBPOLISUR SOCIEDAD DE RESPONS
351  PBBPOLISUR SOCIEDAD DE RESPONS
352  PBBPOLISUR SOCIEDAD DE RESPONS
353  PBBPOLISUR SOCIEDAD DE RESPONS
354  PBBPOLISUR SOCIEDAD DE RESPONS
355  PBBPOLISUR SOCIEDAD DE RESPONS
356  PBBPOLISUR SOCIEDAD DE RESPONS
357  PBBPOLISUR SOCIEDAD DE RESPONS
358  PBBPOLISUR SOCIEDAD DE RESPONS
359  PBBPOLISUR SOCIEDAD DE RESPONS
360  PBBPOLISUR SOCIEDAD DE RESPONS
361  PBBPOLISUR SOCIEDAD DE RESPONS
362  PBBPOLISUR SOCIEDAD DE RESPONS
363  PBBPOLISUR SOCIEDAD DE RESPONS
364  PBBPOLISUR SOCIEDAD DE RESPONS
365  PBBPOLISUR SOCIEDAD DE RESPONS
366  PBBPOLISUR SOCIEDAD DE RESPONS
367  PBBPOLISUR SOCIEDAD DE RESPONS
368  PBBPOLISUR SOCIEDAD DE RESPONS
369  PBBPOLISUR SOCIEDAD DE RESPONS
370  PBBPOLISUR SOCIEDAD DE RESPONS
371  COMPA?IA MOLINERA DEL SUR S. A
372  COMPA?IA MOLINERA DEL SUR S. A
373  COMPA?IA MOLINERA DEL SUR S. A
374  COMPA?IA MOLINERA DEL SUR S. A
375  COMPA?IA MOLINERA DEL SUR S. A
376  COMPA?IA MOLINERA DEL SUR S. A
377  PBBPOLISUR SOCIEDAD DE RESPONS
378  PBBPOLISUR SOCIEDAD DE RESPONS
379  PBBPOLISUR SOCIEDAD DE RESPONS
380  PBBPOLISUR SOCIEDAD DE RESPONS
381  PBBPOLISUR SOCIEDAD DE RESPONS
382  PBBPOLISUR SOCIEDAD DE RESPONS
383  PBBPOLISUR SOCIEDAD DE RESPONS
384  PBBPOLISUR SOCIEDAD DE RESPONS
385  PBBPOLISUR SOCIEDAD DE RESPONS
386  COMPA?IA MOLINERA DEL SUR S. A
387  COMPA?IA MOLINERA DEL SUR S. A
388  COMPA?IA MOLINERA DEL SUR S. A
389  COMPA?IA MOLINERA DEL SUR S. A
390  COMPA?IA MOLINERA DEL SUR S. A
391  PBBPOLISUR SOCIEDAD DE RESPONS
392  PBBPOLISUR SOCIEDAD DE RESPONS
393  COMPA?IA MOLINERA DEL SUR S. A
394  COMPA?IA MOLINERA DEL SUR S. A
395  COMPA?IA MOLINERA DEL SUR S. A
396  PBBPOLISUR SOCIEDAD DE RESPONS
397  PBBPOLISUR SOCIEDAD DE RESPONS
398  PBBPOLISUR SOCIEDAD DE RESPONS
399  PBBPOLISUR SOCIEDAD DE RESPONS
400  PBBPOLISUR SOCIEDAD DE RESPONS
401  PBBPOLISUR SOCIEDAD DE RESPONS
402  PBBPOLISUR SOCIEDAD DE RESPONS
403   TRANSPORTADORA DE GAS DEL SUR
404   TRANSPORTADORA DE GAS DEL SUR
405   TRANSPORTADORA DE GAS DEL SUR
406           BUNGE ARGENTINA S. A.
407           BUNGE ARGENTINA S. A.
408           BUNGE ARGENTINA S. A.
409           BUNGE ARGENTINA S. A.
410           BUNGE ARGENTINA S. A.
411              UNIPAR INDUPA SAIC
412  PBBPOLISUR SOCIEDAD DE RESPONS
413  PBBPOLISUR SOCIEDAD DE RESPONS
414  PBBPOLISUR SOCIEDAD DE RESPONS
415  PBBPOLISUR SOCIEDAD DE RESPONS
416  PBBPOLISUR SOCIEDAD DE RESPONS
417  PBBPOLISUR SOCIEDAD DE RESPONS
418  PBBPOLISUR SOCIEDAD DE RESPONS
419  COMPA?IA MOLINERA DEL SUR S. A
420  COMPA?IA MOLINERA DEL SUR S. A
421  COMPA?IA MOLINERA DEL SUR S. A
422        INDUSTRIAS GRINDOIL S.A.
423        INDUSTRIAS GRINDOIL S.A.
424  PBBPOLISUR SOCIEDAD DE RESPONS
425  PBBPOLISUR SOCIEDAD DE RESPONS
426  PBBPOLISUR SOCIEDAD DE RESPONS
427  PBBPOLISUR SOCIEDAD DE RESPONS
428  PBBPOLISUR SOCIEDAD DE RESPONS
429  PBBPOLISUR SOCIEDAD DE RESPONS
430  PBBPOLISUR SOCIEDAD DE RESPONS
431  PBBPOLISUR SOCIEDAD DE RESPONS
432  PBBPOLISUR SOCIEDAD DE RESPONS
433  PBBPOLISUR SOCIEDAD DE RESPONS
434  COMPA?IA MOLINERA DEL SUR S. A
435  COMPA?IA MOLINERA DEL SUR S. A
436  COMPA?IA MOLINERA DEL SUR S. A
437  COMPA?IA MOLINERA DEL SUR S. A
438           BUNGE ARGENTINA S. A.
439           BUNGE ARGENTINA S. A.
440           BUNGE ARGENTINA S. A.
441           BUNGE ARGENTINA S. A.
442  PBBPOLISUR SOCIEDAD DE RESPONS
443  COMPA?IA MOLINERA DEL SUR S. A
444  COMPA?IA MOLINERA DEL SUR S. A
445  COMPA?IA MOLINERA DEL SUR S. A
446              UNIPAR INDUPA SAIC
447  COMPA?IA MOLINERA DEL SUR S. A
448  COMPA?IA MOLINERA DEL SUR S. A
449           BUNGE ARGENTINA S. A.
450           BUNGE ARGENTINA S. A.
451           BUNGE ARGENTINA S. A.
452           BUNGE ARGENTINA S. A.
453           BUNGE ARGENTINA S. A.
454           BUNGE ARGENTINA S. A.
455           BUNGE ARGENTINA S. A.
456           BUNGE ARGENTINA S. A.
457           BUNGE ARGENTINA S. A.
458           BUNGE ARGENTINA S. A.
459           BUNGE ARGENTINA S. A.
460           BUNGE ARGENTINA S. A.
461           BUNGE ARGENTINA S. A.
462           BUNGE ARGENTINA S. A.
463           BUNGE ARGENTINA S. A.
464           BUNGE ARGENTINA S. A.
465           BUNGE ARGENTINA S. A.
466  COMPA?IA MEGA SOCIEDAD ANONIMA
467  COMPA?IA MEGA SOCIEDAD ANONIMA
468  COMPA?IA MEGA SOCIEDAD ANONIMA
469  COMPA?IA MEGA SOCIEDAD ANONIMA
470  COMPA?IA MEGA SOCIEDAD ANONIMA
471  COMPA?IA MEGA SOCIEDAD ANONIMA
472  COMPA?IA MEGA SOCIEDAD ANONIMA
473  COMPA?IA MEGA SOCIEDAD ANONIMA
474  PBBPOLISUR SOCIEDAD DE RESPONS
475  PBBPOLISUR SOCIEDAD DE RESPONS
476  PBBPOLISUR SOCIEDAD DE RESPONS
477  PBBPOLISUR SOCIEDAD DE RESPONS
478  PBBPOLISUR SOCIEDAD DE RESPONS
479  PBBPOLISUR SOCIEDAD DE RESPONS
480  PBBPOLISUR SOCIEDAD DE RESPONS
481  PBBPOLISUR SOCIEDAD DE RESPONS
482  PBBPOLISUR SOCIEDAD DE RESPONS
483  PBBPOLISUR SOCIEDAD DE RESPONS
484  PBBPOLISUR SOCIEDAD DE RESPONS
485  PBBPOLISUR SOCIEDAD DE RESPONS
486  PBBPOLISUR SOCIEDAD DE RESPONS
487  PBBPOLISUR SOCIEDAD DE RESPONS
488  PBBPOLISUR SOCIEDAD DE RESPONS
489  PBBPOLISUR SOCIEDAD DE RESPONS
490  PBBPOLISUR SOCIEDAD DE RESPONS
491  PBBPOLISUR SOCIEDAD DE RESPONS
492  PBBPOLISUR SOCIEDAD DE RESPONS
493  COMPA?IA MOLINERA DEL SUR S. A
494  COMPA?IA MOLINERA DEL SUR S. A
495  COMPA?IA MOLINERA DEL SUR S. A
496  COMPA?IA MOLINERA DEL SUR S. A
497  COMPA?IA MOLINERA DEL SUR S. A
498  COMPA?IA MOLINERA DEL SUR S. A
499             LA NUEVA MANERA S.A
500           BUNGE ARGENTINA S. A.
501           BUNGE ARGENTINA S. A.
502           BUNGE ARGENTINA S. A.
503           BUNGE ARGENTINA S. A.
504           BUNGE ARGENTINA S. A.
505           BUNGE ARGENTINA S. A.
506           BUNGE ARGENTINA S. A.
507           BUNGE ARGENTINA S. A.
508  PBBPOLISUR SOCIEDAD DE RESPONS
509  PBBPOLISUR SOCIEDAD DE RESPONS
510  PBBPOLISUR SOCIEDAD DE RESPONS
511  PBBPOLISUR SOCIEDAD DE RESPONS
512              UNIPAR INDUPA SAIC
513              UNIPAR INDUPA SAIC
514              UNIPAR INDUPA SAIC
515              UNIPAR INDUPA SAIC
516  COMPA?IA MOLINERA DEL SUR S. A
517  COMPA?IA MOLINERA DEL SUR S. A
518  COMPA?IA MOLINERA DEL SUR S. A
519  COMPA?IA MOLINERA DEL SUR S. A
520  COMPA?IA MOLINERA DEL SUR S. A
521  COMPA?IA MOLINERA DEL SUR S. A
522  COMPA?IA MOLINERA DEL SUR S. A
523  COMPA?IA MOLINERA DEL SUR S. A
524  COMPA?IA MOLINERA DEL SUR S. A
525           BUNGE ARGENTINA S. A.
526           BUNGE ARGENTINA S. A.
527           BUNGE ARGENTINA S. A.
528  PBBPOLISUR SOCIEDAD DE RESPONS
529  PBBPOLISUR SOCIEDAD DE RESPONS
530  PBBPOLISUR SOCIEDAD DE RESPONS
531  PBBPOLISUR SOCIEDAD DE RESPONS
532  PBBPOLISUR SOCIEDAD DE RESPONS
533  PBBPOLISUR SOCIEDAD DE RESPONS
534  PBBPOLISUR SOCIEDAD DE RESPONS
535  PBBPOLISUR SOCIEDAD DE RESPONS
536  PBBPOLISUR SOCIEDAD DE RESPONS
537  PBBPOLISUR SOCIEDAD DE RESPONS
538  PBBPOLISUR SOCIEDAD DE RESPONS
539  PBBPOLISUR SOCIEDAD DE RESPONS
540  PBBPOLISUR SOCIEDAD DE RESPONS
541  PBBPOLISUR SOCIEDAD DE RESPONS
542  PBBPOLISUR SOCIEDAD DE RESPONS
543  PBBPOLISUR SOCIEDAD DE RESPONS
544  PBBPOLISUR SOCIEDAD DE RESPONS
545  COMPA?IA MOLINERA DEL SUR S. A
546  COMPA?IA MOLINERA DEL SUR S. A
547  COMPA?IA MOLINERA DEL SUR S. A
548  COMPA?IA MOLINERA DEL SUR S. A
549  COMPA?IA MOLINERA DEL SUR S. A
550  COMPA?IA MOLINERA DEL SUR S. A

In [ ]:
df =

In [48]:
df = pd.DataFrame({'ARCHIVOS':archivoss,'NACIONALIDAD_TRANSPORTE_X':data})

PAISES_MERCOSUR = ['ARGENTINA', 'BRASIL', 'PARAGUAY', 'URUGUAY', 'VENEZUELA', 'CHILE', 'BOLIVIA']    

df['NACIONALIDAD_TRANSPORTE_X'] = df['NACIONALIDAD_TRANSPORTE_X'].apply(
    lambda x: next((pais for pais in PAISES_MERCOSUR if pais in x), None)
)
df_pdfs_que_no_toman_pais = df[df['NACIONALIDAD_TRANSPORTE_X'].isnull()]['ARCHIVOS']
# archivos que no tienen nacionalidad de transporte

df_pdfs_que_no_toman_pais

NameError: name 'archivoss' is not defined

In [49]:
for archivo in archivos:
    texto = fitz.open(archivo).load_page(0).get_text("text")
    #al texto aplicarle regex para obtener todo el texto entre '/ Nome e endereco do transportado'
    # hasta 7 Aduana, ciudad y pais de partida
    texto_antes = 'Nombre y domicilio del porteador'
    texto_despues = '7 Aduana, ciudad y pais de partida'
    pattern = re.escape(texto_antes) + r"(.*?)" + re.escape(texto_despues)
    matches = re.findall(pattern, texto, re.DOTALL)
    
    # y a matches aplicarle otro regex para obtener el pais del mercosur que encuentre en el texto
    # y si no encuentra nada, poner 'NO ENCONTRADO'
    if matches:
        pais = re.search(r'\b(?:ARGENTINA|BRASIL|PARAGUAY|URUGUAY|VENEZUELA|CHILE|BOLIVIA)\b', matches[0])
        if pais:
            print(pais.group())
        else:
            print('NO ENCONTRADO')
    else:
        print('NO ENCONTRADO')
    
    print('--------------------------------------------------')

ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
BRASIL
--------------------------------------------------
BRASIL
--------------------------------------------------
BRASIL
--------------------------------------------------
BRASIL
--------------------------------------------------
BRASIL
--------------------------------------------------
BRASIL
--------------------------------------------------
BRASIL
--------------------------------------------------
BRASIL
--------------------------------------------------
BRASIL
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
CHILE
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
CHILE
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
BRASIL
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
BRASIL
--------------------------------------------------
BRASIL
--------------------------------------------------
CHILE
--------------------------------------------------
CHILE
--------------------------------------------------
CHILE
--------------------------------------------------
BRASIL
--------------------------------------------------
BRASIL
--------------------------------------------------
BRASIL
--------------------------------------------------
BRASIL
--------------------------------------------------
BRASIL
--------------------------------------------------
BRASIL
--------------------------------------------------
BRASIL
--------------------------------------------------
CHILE
--------------------------------------------------
BRASIL
--------------------------------------------------
BRASIL
--------------------------------------------------
BRASIL
--------------------------------------------------
BRASIL
--------------------------------------------------
BRASIL
--------------------------------------------------
BRASIL
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
BRASIL
--------------------------------------------------
BRASIL
--------------------------------------------------
BRASIL
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
URUGUAY
--------------------------------------------------
BRASIL
--------------------------------------------------
BRASIL
--------------------------------------------------
BRASIL
--------------------------------------------------
BRASIL
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
ARGENTINA
--------------------------------------------------
CHILE
--------------------------------------------------
BRASIL
--------------------------------------------------
BRASIL
--------------------------------------------------
BRASIL
--------------------------------------------------
BRASIL
--------------------------------------------------
CHILE
--------------------------------------------------
CHILE
--------------------------------------------------
CHILE
--------------------------------------------------

In [ ]:
def get_NACIONALIDAD_TRANSPORTE(archivos_validos: list[str]):
    data = []
    for archivo in archivos_validos:
        pdf = fitz.open(archivo).load_page(0)
        # Load the page content as text
        page_text = pdf.get_text("text")

        #print(page_text)

        texto_antes = 'Nombre y domicilio del porteador'
        texto_despues = '7 Aduana, ciudad y pais de partida'
        pattern = re.escape(texto_antes) + r"(.*?)" + re.escape(texto_despues)
        
        matches = re.findall(pattern, page_text, re.DOTALL)

        if matches:
            pais = re.search(r'\b(?:ARGENTINA|BRASIL|PARAGUAY|URUGUAY|VENEZUELA|CHILE|BOLIVIA)\b', matches[0])
            if pais:
                data.append(pais.group())
            else:
                data.append('NO ENCONTRADO')
        else:
            data.append('NO ENCONTRADO')
    return data

In [50]:
archivos_validos = archivos
data = get_NACIONALIDAD_TRANSPORTE(archivos_validos)
len(data)

NameError: name 'get_NACIONALIDAD_TRANSPORTE' is not defined

In [ ]:
df = pd.read_excel('data/peterlangula.xlsx', engine='openpyxl', sheet_name='Sheet1', header=0)
df.head(10)

In [52]:
def extraer_factura_y_orden(descripcion_mercancia: pd.Series) -> pd.DataFrame:
    """ Obtiene la factura y orden de la descripcion de mercancia

    Args:
        descripcion_mercancia (pd.Series): _description_

    Returns:
        pd.DataFrame: _description_
    """
    # Definir las expresiones regulares
    regex_factura_proforma = re.compile(r'FACTURA\s+PROFORMA\s+(\d{6,})', re.IGNORECASE)
    regex_factura_nro = re.compile(r'FACTURA\s+NRO\.\s+([A-Z0-9-]{10,})', re.IGNORECASE)
    regex_factura_exportacion = re.compile(r'FACTURA\s+(?:DE\s+)?EXPORTACION(?:\s+E)?\s+([0-9]{4,5}-[A-Z0-9]{8})', re.IGNORECASE)
    regex_fact_de_exp = re.compile(r'FACT(?:\.|URA)?\.?DE\.?EXP\.?\s*([0-9]{4}-[0-9]{8})', re.IGNORECASE)
    regex_factura_simple = re.compile(r'\b([0-9]{4}-[0-9]{8})\b')
    regex_orden = re.compile(r'ORDEN\s+(\d{9,10})', re.IGNORECASE)

    resultados = []

    for desc in descripcion_mercancia:
        if not isinstance(desc, str):
            resultados.append({'FACTURA Nº': '', 'ORDEN': ''})
            continue

        desc_upper = desc.upper()
        desc_upper = re.sub(r'SHIPMENT\s*:\s*\d+', '', desc_upper)

        factura = ''
        orden = ''
        
        # Buscar FACTURA PROFORMA
        if match := regex_factura_proforma.search(desc_upper):
            factura = match.group(1)  
            orden = match.group(1)
        else:
            match_orden = regex_orden.search(desc_upper)
            if match_orden:
                orden = match_orden.group(1)
            if match := regex_factura_exportacion.search(desc_upper):
                factura = match.group(1)
            else:
                if match := regex_factura_nro.search(desc_upper):
                    factura = match.group(1)
                else:
                    if match := regex_fact_de_exp.search(desc_upper):
                        factura = match.group(1)
                    else:
                        if match := regex_factura_simple.search(desc_upper):
                            factura = match.group(1)
        resultados.append({'FACTURA Nº': factura, 'ORDEN': orden})

    return pd.DataFrame(resultados)

def agregar_factura_y_orden(df: pd.DataFrame) -> pd.DataFrame:
    """
        Toma un DataFrame, elimina la columna 'descripcion_mercancia',
        extrae las columnas 'FACTURA Nº' y 'ORDEN' usando la función extraer_factura_y_orden,
        y las inserta en el DataFrame.

        Args:
            df (pd.DataFrame): DataFrame original.

        Returns:
            pd.DataFrame: DataFrame modificado con las columnas 'FACTURA Nº' y 'ORDEN'.
    """
    # Extraer 'FACTURA Nº' y 'ORDEN' de 'descripcion_mercancia'
    factura_orden_df = extraer_factura_y_orden(df['descripcion_mercancia'])
        
    # Eliminar la columna 'descripcion_mercancia'
    df = df.drop(columns=['descripcion_mercancia'])
        
        # Concatenar el DataFrame original con las nuevas columnas
    df = pd.concat([df, factura_orden_df], axis=1)
        
    return df

In [53]:
df = agregar_factura_y_orden(df)

KeyError: 'descripcion_mercancia'

In [54]:
df.head(10)

                       EXPORTADOR
0  PBBPOLISUR SOCIEDAD DE RESPONS
1  PBBPOLISUR SOCIEDAD DE RESPONS
2  PBBPOLISUR SOCIEDAD DE RESPONS
3  PBBPOLISUR SOCIEDAD DE RESPONS
4  PBBPOLISUR SOCIEDAD DE RESPONS
5  PBBPOLISUR SOCIEDAD DE RESPONS
6  PBBPOLISUR SOCIEDAD DE RESPONS
7  PBBPOLISUR SOCIEDAD DE RESPONS
8  PBBPOLISUR SOCIEDAD DE RESPONS
9  PBBPOLISUR SOCIEDAD DE RESPONS

In [ ]:
df = pd.read_excel("testing-data/data.xlsx",engine="openpyxl")

In [ ]:
for empresa in df["TRANSPORTE CAMPO 1"]:
    
    nombre_empresa_formateado = re.sub(r'[\\/:*?"<>|]', '', empresa).strip()
    print(nombre_empresa_formateado)

In [55]:
empresa = 'MOYA Y COMPA?IA LIMITADA'
empresa
nombre_empresa_formateado = re.sub(r'[\\/:*?"<>|]', '', empresa).strip()
nombre_empresa_formateado

'MOYA Y COMPAIA LIMITADA'

In [ ]:
empresa

In [56]:
df['TRANSPORTE CAMPO 9']
# Sacar saltos de línea
descs = df['TRANSPORTE CAMPO 9']


df['TRANSPORTE CAMPO 9'] = df['TRANSPORTE CAMPO 9'].str.replace('\n', '', regex=True)# Compilar el patrón regex
patron = re.compile(r'(?: & -|-).*', re.IGNORECASE)

df['TRANSPORTE CAMPO 9'] = df['TRANSPORTE CAMPO 9'].str.replace(patron, '', regex=True).str.strip()
# Reemplazar todo lo que coincide con el patrón
df['TRANSPORTE CAMPO 9']

KeyError: 'TRANSPORTE CAMPO 9'

In [ ]:
df_mic_y_tp1 = df[['TRANSPORTE CAMPO 1', 'MIC - DTA']]
df_mic_y_tp1

In [ ]:
empresa = 'CARLOS PATRON S.A.'
lista_mics_de_empresa = list(df[df["TRANSPORTE CAMPO 1"] == empresa]['MIC - DTA'])
lista_mics_de_empresa

In [ ]:
path = 'D:/Moggia/pdfs-to-excel/testing-data/03 MARZO 2025'
files_with_path = [os.path.join(path, file) for file in list(os.walk(path))[0][2] if file.endswith('.pdf')]
files_with_path

In [ ]:
empresa

lista_mics_de_empresa = list(df[df["TRANSPORTE CAMPO 1"] == empresa]['MIC - DTA'])
lista_mics_de_empresa

In [ ]:
rutas_filtradas = [ruta for ruta in files_with_path if any(mic in ruta for mic in lista_mics_de_empresa)]
rutas_filtradas

In [57]:
# 1. Librerías necesarias
import os
import shutil
import pandas as pd
import re
from fuzzywuzzy import fuzz, process



# 2. Función para estandarizar razones sociales
def estandarizar_razon_social(razon_social):
    if pd.isna(razon_social):
        return ""
    razon = razon_social.upper()
    razon = razon.replace(",", "")
    razon = razon.replace(".", "")
    razon = re.sub(r'\bSOCIEDAD\s+ANONIMA\b', 'SA', razon)
    razon = re.sub(r'\bSOCIEDAD\s+ANÓNIMA\b', 'SA', razon)
    razon = re.sub(r'\bS\s*A\b', 'SA', razon)
    razon = re.sub(r'\bSOCIEDAD\s+RESPONSABILIDAD\s+LIMITADA\b', 'SRL', razon)
    razon = re.sub(r'\bS\s*R\s*L\b', 'SRL', razon)
    razon = re.sub(r'\s+', ' ', razon).strip()
    return razon

# 3. Cargar datos
data = pd.read_excel("testing-data/AG-test/AG.xlsx", engine="openpyxl")
df = data[["TRANSPORTE CAMPO 1"]].rename(columns={"TRANSPORTE CAMPO 1": "Razon Social"})

# 4. Estandarizar razones sociales
df["Razon Social Estandarizada"] = df["Razon Social"].apply(estandarizar_razon_social)

# 5. Agrupar usando fuzzy matching
razones_unicas = []

# Threshold de similitud: 90%
threshold = 85

for razon in df["Razon Social Estandarizada"]:
    match = process.extractOne(razon, razones_unicas, scorer=fuzz.token_sort_ratio)
    
    if match is None or match[1] < threshold:
        razones_unicas.append(razon)
    else:
        # Si encuentra una similar, la consideramos ya incluida
        continue

# 6. Asignar a qué grupo pertenece cada razón social
def asignar_grupo(razon, razones_unicas, threshold=90):
    match = process.extractOne(razon, razones_unicas, scorer=fuzz.partial_ratio)
    if match and match[1] >= threshold:
        return match[0]
    else:
        return razon

df["Grupo Razon Social"] = df["Razon Social Estandarizada"].apply(lambda x: asignar_grupo(x, razones_unicas))



# 8. Eliminar duplicados finales
df_unico = df.sort_values("Razon Social").groupby("Grupo Razon Social", as_index=False).first()[["Razon Social"]]


# Mostrar solo una vez cada razón social final
df_unico

c:\Users\rapha\AppData\Local\Programs\Python\Python313\Lib\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')

FileNotFoundError: [Errno 2] No such file or directory: 'testing-data/AG-test/AG.xlsx'

In [ ]:
df = pd.read_excel("testing-data/AG-test/AG.xlsx", engine="openpyxl")
empresas = list(df["TRANSPORTE CAMPO 1"].unique())

df.tail()

In [ ]:
list(empresas)

In [ ]:
import pandas as pd
from rapidfuzz import process, fuzz

df_empresa_nombes = pd.DataFrame({'original': empresas})

nombres_base = []
mapeo_estandar = {}
umbral = 85  # Nivel de similitud


for nombre in df_empresa_nombes['original'].unique():
    match = process.extractOne(nombre, nombres_base, scorer=fuzz.token_sort_ratio)
    
    if match and match[1] >= umbral:
        mapeo_estandar[nombre] = match[0]
    else:
        mapeo_estandar[nombre] = nombre
        nombres_base.append(nombre)

# Aplicar mapeo al DataFrame
df_empresa_nombes['empresa_estandarizada'] = df_empresa_nombes['original'].map(mapeo_estandar)

# Ver resultado
df_empresa_nombes['empresa_estandarizada'].unique()

In [ ]:
from rapidfuzz import process, fuzz
import pandas as pd

def estandarizar_empresas(columna_transporte):
    """
    Función que estandariza los nombres de empresas en la columna 'TRANSPORTE CAMPO 1'.

    Args:
        columna_transporte (pd.Series): Columna con los nombres originales de las empresas.

    Returns:
        pd.DataFrame: DataFrame con las columnas 'original' y 'empresa_estandarizada'.
    """
    nombres_base = []
    mapeo_estandar = {}
    umbral = 85  # Nivel de similitud

    for nombre in columna_transporte.unique():
        match = process.extractOne(nombre, nombres_base, scorer=fuzz.token_sort_ratio)
        
        if match and match[1] >= umbral:
            mapeo_estandar[nombre] = match[0]
        else:
            mapeo_estandar[nombre] = nombre
            nombres_base.append(nombre)

    # Crear el DataFrame con los resultados
    df_resultado = pd.DataFrame({
        'original': columna_transporte,
        'empresa_estandarizada': columna_transporte.map(mapeo_estandar)
    })

    return df_resultado

In [ ]:
estandarizar_empresas(df['TRANSPORTE CAMPO 1'])

### DETALLE DE OPERACIONES

In [ ]:
from openpyxl import Workbook
from openpyxl.drawing.image import Image
from openpyxl.styles import Alignment, Font, PatternFill, Border, Side
from openpyxl.utils import get_column_letter

# Crear el Workbook
wb = Workbook()
ws = wb.active
ws.title = "Detalle Operaciones"

# Fondo blanco
white_fill = PatternFill(start_color="FFFFFF", end_color="FFFFFF", fill_type="solid")



# Pintar fondo blanco de A1 a E12
for row in range(1, 13):
    for col in range(1, 6):
        cell = ws.cell(row=row, column=col)
        cell.fill = white_fill

# Borde grueso del recuadro A6:E12
thick_side = Side(border_style="thick")
for row in range(6, 13):
    for col in range(1, 6):
        col_letter = get_column_letter(col)
        ws[f"{col_letter}{row}"].border = Border(
            top=thick_side if row == 6 else None,
            bottom=thick_side if row == 12 else None,
            left=thick_side if col == 1 else None,
            right=thick_side if col == 5 else None
        )

# Título principal
ws.merge_cells('A7:E7')
ws['A7'] = 'DETALLE DE OPERACIONES'
ws['A7'].alignment = Alignment(horizontal='center', vertical='center')
ws['A7'].font = Font(size=16, bold=True, underline='single')
ws['A7'].fill = white_fill

# Mes y Año
ws['A8'] = 'MES:'
ws['A8'].alignment = Alignment(horizontal='right', vertical='center')
ws['A8'].font = Font(bold=True)
ws['A8'].fill = white_fill

ws['B8'] = ''  # Espacio para completar el mes
ws['B8'].fill = white_fill

ws['D8'] = 'AÑO:'
ws['D8'].alignment = Alignment(horizontal='right', vertical='center')
ws['D8'].font = Font(bold=True)
ws['D8'].fill = white_fill

ws['E8'] = ''  # Espacio para completar el año
ws['E8'].fill = white_fill

# Texto largo
texto_largo = "Detalle de las operaciones en las que hemos actuado en carácter de Agentes de Transporte"
texto_corto = "Aduanero de la firma:"

ws.merge_cells('A9:E9')
ws['A9'] = texto_largo
ws['A9'].alignment = Alignment(horizontal='left', vertical='center', wrap_text=True)
ws['A9'].font = Font(size=11)
ws['A9'].fill = white_fill

# Aduanero de la firma
ws['A10'] = texto_corto
ws['A10'].alignment = Alignment(horizontal='left', vertical='center')
ws['A10'].font = Font(size=11)
ws['A10'].fill = white_fill

ws['B10'] = ''  # Espacio para nombre de firma
ws['B10'].fill = white_fill

# Total de unidades
ws['A11'] = "Total de unidades:"
ws['A11'].alignment = Alignment(horizontal='left', vertical='center')
ws['A11'].font = Font(size=11)
ws['A11'].fill = white_fill

ws['B11'] = ''  # Espacio para completar total
ws['B11'].fill = white_fill

# Encabezados de tabla (fila 13)
column_headers = ['FECHA', 'MIC-DTA', 'D.D.T.', 'ORDEN', 'FACTURA N°']
header_fill = PatternFill(start_color="CCFFFF", end_color="CCFFFF", fill_type="solid")  # Celeste claro

for col_num, header in enumerate(column_headers, start=1):
    col_letter = get_column_letter(col_num)
    cell = ws[f'{col_letter}13']
    cell.value = header
    cell.alignment = Alignment(horizontal='center', vertical='center')
    cell.font = Font(bold=True)
    cell.fill = header_fill
    cell.border = Border(
        left=Side(style='thin'),
        right=Side(style='thin'),
        top=Side(style='thin'),
        bottom=Side(style='thin')
    )

# Los datos vienen por parámetro
datos = []

# Borde fino
thin_border = Border(
    left=Side(style='thin'),
    right=Side(style='thin'),
    top=Side(style='thin'),
    bottom=Side(style='thin')
)

# Escribir los datos a partir de la fila 14
for fila_idx, fila_dato in enumerate(datos, start=14):
    for col_idx, valor in enumerate(fila_dato, start=1):
        cell = ws.cell(row=fila_idx, column=col_idx)
        cell.value = valor
        cell.alignment = Alignment(horizontal='center', vertical='center')
        cell.border = thin_border
        cell.fill = white_fill
    ws.row_dimensions[fila_idx].height = 20

# Ajustar ancho de columnas
column_widths = [20, 16, 18, 16, 16]
for i, width in enumerate(column_widths, start=1):
    ws.column_dimensions[get_column_letter(i)].width = width

# Centrado de impresión y ajustes
ws.page_setup.horizontalCentered = True
ws.page_setup.fitToWidth = 1
ws.page_setup.fitToHeight = 0

# Actualizar área de impresión
ultima_fila = 13 + len(datos)
ws.print_area = f"A1:E{ultima_fila}"

# Guardar
wb.save('plantilla_detalle_operaciones.xlsx')

In [ ]:


import openpyxl
from openpyxl import load_workbook



# Cargar el libro de trabajo existente
wb = load_workbook('assets/plantilla_detalle_operaciones.xlsx')

# cargar la hoja activa
ws = wb.active
# 1 paso
mes = 'marzo'

ws['B8'] = mes
ws['B8'].alignment = Alignment(horizontal='left', vertical='center')


# 2 paso
anio = 2025

ws['E8'] = anio
ws['E8'].alignment = Alignment(horizontal='left', vertical='center')

nombre_firma = 'PEPE 123'

ws['B10'] = ''

# 3 paso (meter los datos)
wb.save('assets/plantilla_detalle_operaciones_actualizada.xlsx')





# esto va despues de ingresar los datos al excel
# 4 paso
total_unidades = 15
ws['B11'] = total_unidades
ws['B11'].alignment = Alignment(horizontal='left', vertical='center')

In [ ]:
import shutil

df = pd.read_excel('testing-data/AG-test2/AG.xlsx', engine='openpyxl')
# Crear una copia del archivo existente

ruta_original = 'assets/plantilla_detalle_operaciones.xlsx'
ruta_copia = 'assets/plantilla_detalle_operaciones_copia.xlsx'
shutil.copy(ruta_original, ruta_copia)

# Crear un nuevo archivo basado en la copia
with pd.ExcelWriter(ruta_copia, engine='openpyxl', mode='a', if_sheet_exists='overlay') as writer:
    df[['FECHA CARGA', 'MIC - DTA', 'D.D.T', 'ORDEN', 'FACTURA Nº']].to_excel(writer, sheet_name='Detalle Operaciones', index=False, startrow=13, startcol=0, header=False)

In [ ]:
import os
import shutil
import pandas as pd
from openpyxl import load_workbook
from openpyxl.styles import Alignment

import os
from os.path import abspath
import shutil
import sys
import win32com.client 
from shutil import rmtree
import pandas as pd
from openpyxl import load_workbook
from openpyxl.styles import Alignment
from xlwings import Book

def get_asset_path(relative_path):
    """Obtiene la ruta correcta del archivo, ya sea en desarrollo o en el ejecutable."""
    try:
        # Cuando se ejecuta como ejecutable empaquetado
        base_path = sys._MEIPASS
    except AttributeError:
        # Cuando se ejecuta como script en desarrollo
        base_path = os.path.abspath(".")
    return os.path.join(base_path, relative_path)

def main_process_detalle_operacion(ruta_excel_base, ruta_destino, excel_datos, anio, mes):
    """
    Genera un Excel con detalle de operaciones a partir de una plantilla.

    Args:
        ruta_excel_base (str): Ruta de la plantilla base (siempre será 'assets/plantilla_detalle_operaciones.xlsx').
        ruta_destino (str): Carpeta donde se guardará el archivo resultante.
        excel_datos (str): Ruta del archivo Excel con los datos.
        anio (int): Año a insertar.
        mes (str): Mes a insertar.
    """
    ruta_excel_base = get_asset_path(ruta_excel_base)

    # Crear nombre del nuevo archivo
    nombre_empresa = os.path.basename(excel_datos).split('AG-')[1].split('.xlsx')[0]
    nombre_archivo = "Detalle Operaciones " + nombre_empresa + ".xlsx"
    ruta_final = os.path.join(ruta_destino, nombre_archivo)

    # Copiar plantilla a destino
    shutil.copy(ruta_excel_base, ruta_final)

    # Abrir archivo copiado
    wb = load_workbook(ruta_final)
    wb.template = False
    ws = wb.active
    # Insertar mes y año
    ws['B8'] = mes
    ws['B8'].alignment = Alignment(horizontal='left', vertical='center')

    ws['E8'] = anio
    ws['E8'].alignment = Alignment(horizontal='left', vertical='center')

    # Nombre de la firma (harcodeado por ahora)
    ws['B10'] = nombre_empresa
    ws['B10'].alignment = Alignment(horizontal='left', vertical='center')

    # Leer datos desde el archivo Excel de datos
    df = pd.read_excel(excel_datos, engine='openpyxl')
    df_final = df.loc[:, ['FECHA CARGA', 'MIC - DTA', 'D.D.T', 'ORDEN', 'FACTURA Nº']]
    df_final['FECHA CARGA'] = pd.to_datetime(df_final['FECHA CARGA'], dayfirst=True, errors='coerce')
    # Ordenar por la columna 'FECHA CARGA' de menor a mayor
    df_final = df_final.sort_values(by='FECHA CARGA', ascending=True).reset_index(drop=True)
    df_final['FECHA CARGA'] = df_final['FECHA CARGA'].dt.strftime('%d/%m/%Y')

    # Insertar total de unidades
    total_unidades = len(df_final)
    ws['B11'] = total_unidades
    ws['B11'].alignment = Alignment(horizontal='left', vertical='center')

    # Insertar datos desde fila 14 (índice 13)
    for i, row in df_final.iterrows():
        for j, campo in enumerate(['FECHA CARGA', 'MIC - DTA', 'D.D.T', 'ORDEN', 'FACTURA Nº']):
            ws.cell(row=14 + i, column=1 + j, value=row[campo])

    # Guardar
    wb.save(ruta_final)
    
    wb = Book(ruta_final)
    ws =  wb.sheets[0]
    img = os.path.abspath('assets/imagen.jpg')
    ws.pictures.add(
        img,
        top=ws.range('A1').top,
        left=ws.range('A1').left,
        width=ws.range('E5').left + ws.range('E5').width - ws.range('A1').left,
        height=ws.range('E5').top + ws.range('E5').height - ws.range('A1').top
)
    print(f"Archivo guardado en: {ruta_final}")

In [ ]:
main_process_detalle_operacion(
    'assets/plantilla_detalle_operaciones_temp1.xlsx', 
    'testing-data/', 
    'testing-data/AGtestDetalle/TRANSPORTES GRACA SA/AG-TRANSPORTES GRACA SA.xlsx', 
    2025, 
    'marzo'
)

In [ ]:
df_test = pd.read_excel('testing-data/AGtestDetalle/TRANSPORTES GRACA SA/AG-TRANSPORTES GRACA SA.xlsx', engine='openpyxl')
df_test['FECHA CARGA'].sort_values(ascending=True)

In [ ]:
import pandas as pd
# Convertir la columna 'FECHA CARGA' a formato datetime
df = pd.read_excel('testing-data/AGtestDetalle/TRANSPORTES GRACA SA/AG-TRANSPORTES GRACA SA.xlsx', engine='openpyxl')
df['FECHA CARGA'] = pd.to_datetime(df['FECHA CARGA'], dayfirst=True, errors='coerce')

# Obtener el mes y el año únicos
mes = df['FECHA CARGA'].dt.month.unique()[0]
anio = df['FECHA CARGA'].dt.year.unique()[0]

meses = [
        "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio",
        "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"
        ]

mes = meses[mes - 1]  
mes, anio